[package]
name = "volparossa-helper"
description = "Minimal privileged network helper for VOLPAROSSA"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
blake3.workspace = true
libc.workspace = true
netlink-sys.workspace = true
nix = { workspace = true, features = ["sched"] }
prost.workspace = true
socket2.workspace = true
rand_core.workspace = true
rustix.workspace = true
subtle.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
volparossa-linux-uapi = { path = "../volparossa-linux-uapi", version = "=0.1.0" }
volparossa-mptcp = { path = "../volparossa-mptcp", version = "=0.1.0" }
volparossa-routing = { path = "../volparossa-routing", version = "=0.1.0" }
volparossa-wireguard = { path = "../volparossa-wireguard", version = "=0.1.0" }
zeroize.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
