//! Owner-enabled continuous public training, independent source selection and durable sharing.
//! Every execution remains bounded; there is no hidden model download or private-cache intake.

mod evaluation;
mod publication;
mod seed;
mod storage;
#[cfg(test)]
mod tests;

use std::{
    collections::BTreeSet,
    path::{Path, PathBuf},
    time::{Duration, SystemTime, UNIX_EPOCH},
};

use anyhow::{Context, Result, ensure};
use clap::Args;
use ed25519_dalek::VerifyingKey;
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};
use tokio::sync::watch;
use volparossa_content::SignedManifest;

use super::{
    private_directory, read_file,
    spare_capacity::{Budget, Decision},
    train_cycle,
};
use crate::content::{self, Limits};
use storage::{Snapshot, Store};

const MAX_SOURCES: usize = 128;
const RETAINED_CYCLES: usize = 8;

#[derive(Debug, Args)]
pub(crate) struct Options {
    /// Version-1 JSON public-source list, selected independently of cache inventory.
    #[arg(long)]
    plan: PathBuf,
    /// New private persistent loop directory, or its exact existing directory with --resume.
    #[arg(long)]
    directory: PathBuf,
    #[arg(long)]
    resume: bool,
    /// Existing explicitly provisioned runtime; this command installs nothing.
    #[arg(long)]
    runtime_root: PathBuf,
    #[arg(long)]
    model_root: PathBuf,
    /// Existing native agent-owned cache; sources absent here still get requested.
    #[arg(long)]
    cache: PathBuf,
    /// Optional explicitly imported compatible initial adapter; later cycles reuse their predecessor.
    #[arg(long, conflicts_with = "seed")]
    adapter_root: Option<PathBuf>,
    /// JSON with independently trusted adapter/dataset publishers and names for an initial peer update.
    #[arg(long, conflicts_with = "adapter_root")]
    seed: Option<PathBuf>,
    #[arg(long, default_value_t=8, value_parser=clap::value_parser!(u16).range(1..=64))]
    steps: u16,
    #[arg(long, default_value_t=2, value_parser=clap::value_parser!(u16).range(1..=2))]
    threads: u16,
    /// Original wall deadline per worker, never enlarged by pauses or subsequent cycles.
    #[arg(long, default_value_t=600, value_parser=clap::value_parser!(u16).range(1..=600))]
    max_seconds: u16,
    /// Stop after this many new cycle attempts; omitted keeps watching until owner cancellation.
    #[arg(long, value_parser=clap::value_parser!(u16).range(1..=256))]
    max_cycles: Option<u16>,
    #[arg(long, default_value_t=60, value_parser=clap::value_parser!(u16).range(1..=3600))]
    poll_seconds: u16,
    /// Explicitly allow more training on an unchanged source; otherwise require a newer revision.
    #[arg(long)]
    repeat_sources: bool,
    /// Enable automatic publication under this owner-local adapter name.
    #[arg(long, value_parser=content::parse_content_name, requires_all=["publication_key","identity","passphrase_file","publish_cache"])]
    publish_name: Option<String>,
    #[arg(long, value_parser=content::parse_publisher_key, requires="publish_name")]
    publication_key: Option<VerifyingKey>,
    /// Existing encrypted owner identity; never generated by the loop.
    #[arg(long, requires = "publish_name")]
    identity: Option<PathBuf>,
    /// Explicit private passphrase file; background execution never prompts interactively.
    #[arg(long, requires = "publish_name")]
    passphrase_file: Option<PathBuf>,
    /// Existing owner-owned cache for new signed publications, separate from the agent cache.
    #[arg(long, requires = "publish_name")]
    publish_cache: Option<PathBuf>,
    #[arg(long, default_value_t=1, value_parser=clap::value_parser!(u64).range(1..))]
    first_publication_revision: u64,
    /// Explicitly start the persistent background service; default only previews its enrollment.
    #[arg(long)]
    execute: bool,
    #[command(flatten)]
    limits: Limits,
}

#[derive(Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct Plan {
    version: u32,
    sources: Vec<Source>,
}

#[derive(Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct Source {
    publisher_key: String,
    name: String,
    #[serde(default)]
    min_revision: Option<u64>,
    #[serde(default)]
    manifest_id: Option<String>,
}

impl Source {
    fn key(&self) -> Result<VerifyingKey> {
        content::parse_publisher_key(&self.publisher_key).map_err(anyhow::Error::msg)
    }
    fn manifest(&self) -> Result<Option<[u8; 32]>> {
        self.manifest_id
            .as_ref()
            .map(|value| {
                ensure!(super::is_hex(value, 64), "train_loop_manifest_id");
                let mut bytes = [0; 32];
                hex::decode_to_slice(value, &mut bytes)?;
                ensure!(bytes != [0; 32], "train_loop_manifest_id");
                Ok(bytes)
            })
            .transpose()
    }
}

#[derive(Serialize, Deserialize, Default)]
#[serde(deny_unknown_fields)]
struct SourceProgress {
    revision: Option<u64>,
    next_attempt: u64,
}

#[derive(Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
enum Phase {
    Running,
    Trained,
    PublishPending,
    Complete,
    Failed,
    PublicationExpired,
    Rejected,
}

#[derive(Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct Cycle {
    sequence: u64,
    source: usize,
    phase: Phase,
    snapshot: Option<Snapshot>,
    #[serde(default)]
    publication: Option<Value>,
    next_publication_attempt: u64,
}

#[derive(Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct State {
    version: u32,
    next_sequence: u64,
    cursor: usize,
    completed: u64,
    promoted: u64,
    rejected: u64,
    latest: Option<u64>,
    sources: Vec<SourceProgress>,
    cycles: Vec<Cycle>,
    garbage: Vec<u64>,
    seed: Option<Value>,
}

impl State {
    fn new(count: usize) -> Self {
        Self {
            version: 2,
            next_sequence: 1,
            cursor: 0,
            completed: 0,
            promoted: 0,
            rejected: 0,
            latest: None,
            sources: (0..count).map(|_| SourceProgress::default()).collect(),
            cycles: Vec::new(),
            garbage: Vec::new(),
            seed: None,
        }
    }
    fn select(&self, plan: &Plan, repeat: bool, time: u64) -> Option<usize> {
        (0..plan.sources.len())
            .map(|offset| (self.cursor + offset) % plan.sources.len())
            .find(|index| {
                let progress = &self.sources[*index];
                progress.next_attempt <= time
                    && (repeat
                        || progress.revision.is_none()
                        || plan.sources[*index].manifest_id.is_none())
                    && (repeat || progress.revision != Some(u64::MAX))
            })
    }
}

struct Activity {
    receiver: watch::Receiver<bool>,
    listener: tokio::task::JoinHandle<()>,
}
impl Activity {
    fn new() -> Result<Self> {
        use tokio::signal::unix::{SignalKind, signal};
        let mut interrupt = signal(SignalKind::interrupt())?;
        let mut terminate = signal(SignalKind::terminate())?;
        let (sender, receiver) = watch::channel(true);
        let listener = tokio::spawn(async move {
            tokio::select! { _=interrupt.recv()=>{}, _=terminate.recv()=>{} }
            let _ = sender.send(false);
        });
        Ok(Self { receiver, listener })
    }
}
impl Drop for Activity {
    fn drop(&mut self) {
        self.listener.abort();
    }
}

fn active(activity: &watch::Receiver<bool>) -> bool {
    *activity.borrow() && activity.has_changed().is_ok()
}
fn now() -> Result<u64> {
    Ok(SystemTime::now().duration_since(UNIX_EPOCH)?.as_secs())
}

fn enrollment(args: &Options) -> Result<(Plan, Value)> {
    let plan: Plan = serde_json::from_slice(&read_file(&args.plan, 64 * 1024)?)?;
    ensure!(
        plan.version == 1 && (1..=MAX_SOURCES).contains(&plan.sources.len()),
        "train_loop_sources"
    );
    let mut distinct = BTreeSet::new();
    for source in &plan.sources {
        let key = source.key()?;
        source.manifest()?;
        content::parse_content_name(&source.name).map_err(anyhow::Error::msg)?;
        ensure!(
            source.min_revision != Some(0)
                && distinct.insert((key.to_bytes(), source.name.clone())),
            "train_loop_duplicate_source"
        );
    }
    for path in [
        &args.directory,
        &args.runtime_root,
        &args.model_root,
        &args.cache,
    ]
    .into_iter()
    .chain(args.adapter_root.iter())
    .chain(args.identity.iter())
    .chain(args.passphrase_file.iter())
    .chain(args.publish_cache.iter())
    {
        ensure!(path.is_absolute(), "train_loop_absolute_paths");
        if path != &args.directory {
            ensure!(
                !path.starts_with(&args.directory) && !args.directory.starts_with(path),
                "train_loop_directory_overlap"
            );
        }
    }
    let selection = json!({"version":1,"sources":plan.sources,"runtime_root":args.runtime_root,"model_root":args.model_root,
        "cache":args.cache,"initial_adapter_root":args.adapter_root,"steps":args.steps,"threads":args.threads,
        "max_worker_seconds":args.max_seconds,"repeat_sources":args.repeat_sources,"limits":args.limits.configuration(),
        "publish_name":args.publish_name,"publication_key":args.publication_key.map(|key|hex::encode(key.as_bytes())),
        "identity":args.identity,"passphrase_file":args.passphrase_file,"publish_cache":args.publish_cache,
        "first_publication_revision":args.first_publication_revision,"seed":seed::selection(args)?,"source_choice_uses_cache_inventory":false,
        "quality_policy":"source-heldout-loss-v1",
        "private_data_supported":false,"code_or_model_downloads":false,"automatic_model_quality_claimed":false});
    Ok((plan, selection))
}

pub(super) async fn run(args: &Options, socket: &Path) -> Result<()> {
    let (plan, selection) = enrollment(args)?;
    if !args.execute {
        println!(
            "{}",
            json!({"operation":"compute_train_loop_plan","execute":false,"selection":selection,
            "resume":args.resume,"max_cycles_this_invocation":args.max_cycles,"network_retrieval":false,"training_executed":false})
        );
        return Ok(());
    }
    ensure!(
        !nix::unistd::geteuid().is_root(),
        "compute_unprivileged_user_required"
    );
    private_directory(&args.runtime_root)?;
    private_directory(&args.model_root)?;
    if let Some(root) = &args.adapter_root {
        private_directory(root)?;
    }
    if let Some(root) = &args.publish_cache {
        private_directory(root)?;
    }
    let store = Store::open(&args.directory, &selection, args.resume)?;
    let mut state: State = store
        .load_state()?
        .map(serde_json::from_value)
        .transpose()?
        .unwrap_or_else(|| State::new(plan.sources.len()));
    recover(&store, &mut state, plan.sources.len())?;
    let activity = Activity::new()?;
    seed::prepare(
        args,
        socket,
        &selection,
        &store,
        &mut state,
        &activity.receiver,
    )
    .await?;
    let mut budget = Budget::new();
    let mut attempts = 0_u64;
    while active(&activity.receiver) {
        publication::pending(args, socket, &store, &mut state, &activity.receiver).await?;
        if args
            .max_cycles
            .is_some_and(|maximum| attempts >= u64::from(maximum))
        {
            break;
        }
        if budget.sample() == Decision::Run {
            if let Some(source) = state.select(&plan, args.repeat_sources, now()?) {
                if make_room(&store, &mut state)? {
                    attempt(
                        args,
                        socket,
                        &plan,
                        &store,
                        &mut state,
                        source,
                        &activity.receiver,
                    )
                    .await?;
                    attempts = attempts
                        .checked_add(1)
                        .context("train_loop_attempt_counter")?;
                    continue;
                }
            }
        }
        let mut receiver = activity.receiver.clone();
        tokio::select! { _=receiver.changed()=>{}, ()=tokio::time::sleep(Duration::from_millis(250))=>{} }
    }
    store.save_state(&serde_json::to_value(&state)?)?;
    println!(
        "{}",
        json!({"operation":"compute_train_loop","completed_cycles":state.completed,
        "promoted_cycles":state.promoted,"rejected_cycles":state.rejected,"latest_approved_sequence":state.latest,
        "quality_policy":"source-heldout-loss-v1","independent_quality_benchmark":false,
        "attempts_this_invocation":attempts,"owner_cancelled":!active(&activity.receiver),
        "pending_publications":state.cycles.iter().filter(|cycle|matches!(cycle.phase,Phase::Trained|Phase::PublishPending)).count(),
        "private_data_supported":false,"full_b05_claimed":false})
    );
    Ok(())
}

fn recover(store: &Store, state: &mut State, count: usize) -> Result<()> {
    ensure!(
        state.version == 2
            && state.next_sequence > 0
            && state.promoted.checked_add(state.rejected) == Some(state.completed)
            && state.completed < state.next_sequence
            && (state.latest.is_some() == (state.promoted > 0))
            && state.sources.len() == count
            && state.cursor < count
            && state.cycles.len() <= RETAINED_CYCLES
            && state.garbage.len() <= RETAINED_CYCLES,
        "train_loop_state"
    );
    let mut distinct = BTreeSet::new();
    for sequence in &state.garbage {
        ensure!(
            *sequence > 0
                && *sequence < state.next_sequence
                && Some(*sequence) != state.latest
                && distinct.insert(*sequence)
                && !state.cycles.iter().any(|cycle| cycle.sequence == *sequence),
            "train_loop_garbage_state"
        );
        store.prune_sequence(*sequence)?;
    }
    state.garbage.clear();
    for cycle in &mut state.cycles {
        ensure!(
            cycle.source < count
                && cycle.sequence > 0
                && cycle.sequence < state.next_sequence
                && distinct.insert(cycle.sequence),
            "train_loop_cycle_state"
        );
        if cycle.phase == Phase::Running {
            cycle.phase = Phase::Failed;
        }
        if let Some(snapshot) = &cycle.snapshot {
            store.validate_snapshot(cycle.sequence, snapshot)?;
            let decision = evaluation::verify(store, cycle.sequence)?;
            ensure!(
                decision.approved == (cycle.phase != Phase::Rejected)
                    && (cycle.phase != Phase::Rejected || cycle.publication.is_none()),
                "train_loop_evaluation_phase_mismatch"
            );
        }
        ensure!(
            cycle.snapshot.is_some() != matches!(cycle.phase, Phase::Running | Phase::Failed),
            "train_loop_snapshot_required"
        );
    }
    if let Some(latest) = state.latest {
        ensure!(
            state.cycles.iter().any(|cycle| cycle.sequence == latest
                && cycle.snapshot.is_some()
                && cycle.phase != Phase::Rejected),
            "train_loop_latest_missing"
        );
    }
    store.save_state(&serde_json::to_value(state)?)
}

fn make_room(store: &Store, state: &mut State) -> Result<bool> {
    if state.cycles.len() < RETAINED_CYCLES {
        return Ok(true);
    }
    let obsolete = state.cycles.iter().position(|cycle| {
        Some(cycle.sequence) != state.latest
            && matches!(
                cycle.phase,
                Phase::Complete | Phase::Failed | Phase::PublicationExpired | Phase::Rejected
            )
    });
    let Some(index) = obsolete else {
        return Ok(false);
    };
    let sequence = state.cycles[index].sequence;
    // No active worker or unpublished update is selected here. Only exact owned cycle
    // directories are pruned; the current warmstart and failed handoffs stay available.
    state.cycles.remove(index);
    state.garbage.push(sequence);
    // Save the exact disposable target before removing its files. A restart can
    // idempotently finish this cleanup instead of expecting a deleted warmstart.
    store.save_state(&serde_json::to_value(&*state)?)?;
    store.prune_sequence(sequence)?;
    state.garbage.clear();
    store.save_state(&serde_json::to_value(state)?)?;
    Ok(true)
}

async fn attempt(
    args: &Options,
    socket: &Path,
    plan: &Plan,
    store: &Store,
    state: &mut State,
    index: usize,
    activity: &watch::Receiver<bool>,
) -> Result<()> {
    if !active(activity) {
        return Ok(());
    }
    let source = &plan.sources[index];
    let sequence = state.next_sequence;
    let minimum = required_revision(source, &state.sources[index], args.repeat_sources)?;
    let adapter = if let Some(previous) = state.latest {
        let cycle = state
            .cycles
            .iter()
            .find(|cycle| cycle.sequence == previous)
            .context("train_loop_latest_missing")?;
        store.validate_snapshot(
            previous,
            cycle
                .snapshot
                .as_ref()
                .context("train_loop_latest_snapshot")?,
        )?;
        Some(store.cycle_path(previous)?.join("training/adapter"))
    } else {
        seed::adapter(args, state)?
    };
    let options = train_cycle::Options {
        publisher_key: source.key()?,
        dataset_name: source.name.clone(),
        dataset_manifest_id: source.manifest()?,
        min_revision: minimum,
        cache: args.cache.clone(),
        reuse_cache: true,
        runtime_root: args.runtime_root.clone(),
        model_root: args.model_root.clone(),
        adapter_root: adapter,
        output: store.cycle_path(sequence)?,
        steps: args.steps,
        threads: args.threads,
        max_seconds: args.max_seconds,
        spare_capacity: true,
        execute: true,
        limits: args.limits.clone(),
    };
    state.next_sequence = sequence
        .checked_add(1)
        .context("train_loop_sequence_exhausted")?;
    state.cursor = (index + 1) % plan.sources.len();
    state.sources[index].next_attempt = now()?.saturating_add(u64::from(args.poll_seconds));
    state.cycles.push(Cycle {
        sequence,
        source: index,
        phase: Phase::Running,
        snapshot: None,
        publication: None,
        next_publication_attempt: 0,
    });
    store.save_state(&serde_json::to_value(&*state)?)?;
    // Do not select/drop this future on cancellation: the model supervisor must reap.
    let result = train_cycle::execute_cycle(&options, socket, activity.clone()).await;
    let qualified = result.and_then(|_| {
        qualify_cycle(
            store,
            state,
            sequence,
            &options,
            args.publish_name.is_some(),
        )
    });
    if qualified.is_err() {
        state
            .cycles
            .last_mut()
            .context("train_loop_cycle_missing")?
            .phase = Phase::Failed;
        // Model/network errors can contain source text. Record a fixed phase only.
        eprintln!("compute loop_event=cycle_failed");
    }
    store.save_state(&serde_json::to_value(&*state)?)?;
    println!(
        "{}",
        json!({"operation":"compute_train_loop_cycle","sequence":sequence,"source_index":index,
        "completed":qualified.is_ok(),"approved":qualified.as_ref().ok().map(|decision|decision.approved),
        "latest_approved_sequence":state.latest,"quality_policy":"source-heldout-loss-v1",
        "total_completed":state.completed,"selection_used_cache_inventory":false})
    );
    Ok(())
}

fn qualify_cycle(
    store: &Store,
    state: &mut State,
    sequence: u64,
    options: &train_cycle::Options,
    publish: bool,
) -> Result<evaluation::Record> {
    let manifest = SignedManifest::decode(&read_file(
        &options.output.join("dataset.manifest"),
        64 * 1024,
    )?)?;
    let verified = manifest.verify(&options.publisher_key, now()?)?;
    let decision = evaluation::assess(
        store,
        sequence,
        state.latest,
        options.adapter_root.as_deref(),
    )?;
    store.write_cycle_json(
        sequence,
        "evaluation.json",
        &serde_json::to_value(&decision)?,
    )?;
    select_successor(
        state,
        store.snapshot_cycle(sequence)?,
        verified.metadata().revision,
        &decision,
        publish,
    )?;
    Ok(decision)
}

/// Technical completion is separate from promotion. A rejected candidate never
/// replaces the warmstart, enters the publication queue, or retries the same
/// completed source revision by accident; it remains bounded and reclaimable.
fn select_successor(
    state: &mut State,
    snapshot: Snapshot,
    revision: u64,
    decision: &evaluation::Record,
    publish: bool,
) -> Result<()> {
    ensure!(
        decision.predecessor == state.latest,
        "train_loop_evaluation_predecessor"
    );
    let completed = state
        .completed
        .checked_add(1)
        .context("train_loop_completed_exhausted")?;
    let promoted = state
        .promoted
        .checked_add(u64::from(decision.approved))
        .context("train_loop_promoted_exhausted")?;
    let rejected = state
        .rejected
        .checked_add(u64::from(!decision.approved))
        .context("train_loop_rejected_exhausted")?;
    let cycle = state
        .cycles
        .last_mut()
        .context("train_loop_cycle_missing")?;
    ensure!(
        decision.sequence == cycle.sequence && cycle.phase == Phase::Running,
        "train_loop_evaluation_cycle"
    );
    state.sources[cycle.source].revision = Some(revision);
    cycle.snapshot = Some(snapshot);
    cycle.phase = if !decision.approved {
        Phase::Rejected
    } else if publish {
        Phase::Trained
    } else {
        Phase::Complete
    };
    if decision.approved {
        state.latest = Some(cycle.sequence);
    }
    state.completed = completed;
    state.promoted = promoted;
    state.rejected = rejected;
    Ok(())
}

fn required_revision(
    source: &Source,
    progress: &SourceProgress,
    repeat: bool,
) -> Result<Option<u64>> {
    match progress.revision.filter(|_| !repeat) {
        Some(previous) => Ok(Some(
            source.min_revision.unwrap_or(1).max(
                previous
                    .checked_add(1)
                    .context("train_loop_revision_exhausted")?,
            ),
        )),
        None => Ok(source.min_revision),
    }
}
