//! Owner-enabled continuous public training, independent source selection and durable sharing.
//! Every execution remains bounded; there is no hidden model download or private-cache intake.

mod catalogs;
mod evaluation;
mod peer_evaluation;
mod peer_updates;
mod publication;
mod seed;
mod serving;
mod storage;
#[cfg(test)]
mod tests;
mod validation;

use std::{
    collections::BTreeSet,
    path::{Path, PathBuf},
    time::{Duration, SystemTime, UNIX_EPOCH},
};

use anyhow::{Context, Result, ensure};
use clap::Args;
use ed25519_dalek::VerifyingKey;
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};
use tokio::sync::watch;
use volparossa_content::SignedManifest;

use super::{
    private_directory, read_file,
    spare_capacity::{Budget, Decision},
    train_cycle,
};
use crate::content::{self, Limits};
use storage::{Snapshot, Store};

const MAX_SOURCES: usize = 128;
const RETAINED_CYCLES: usize = 8;

#[derive(Debug, Args)]
pub(crate) struct Options {
    /// Public source plan: v1 fixed datasets, or v2 datasets and trusted publisher catalogs.
    #[arg(long)]
    plan: PathBuf,
    /// New private persistent loop directory, or its exact existing directory with --resume.
    #[arg(long)]
    directory: PathBuf,
    #[arg(long)]
    resume: bool,
    /// Existing explicitly provisioned runtime; this command installs nothing.
    #[arg(long)]
    runtime_root: PathBuf,
    #[arg(long)]
    model_root: PathBuf,
    /// Existing native agent-owned cache; sources absent here still get requested.
    #[arg(long)]
    cache: PathBuf,
    /// Optional explicitly imported compatible initial adapter; later cycles reuse their predecessor.
    #[arg(long, conflicts_with = "seed")]
    adapter_root: Option<PathBuf>,
    /// JSON with independently trusted adapter/dataset publishers and names for an initial peer update.
    #[arg(long, conflicts_with = "adapter_root")]
    seed: Option<PathBuf>,
    /// Explicit public peer-adapter channels; adoption requires a pinned validation source.
    #[arg(long)]
    peer_updates: Option<PathBuf>,
    /// Optional exact signed validation-only public source, selected before any training.
    #[arg(long)]
    validation_source: Option<PathBuf>,
    #[arg(long, default_value_t=8, value_parser=clap::value_parser!(u16).range(1..=64))]
    steps: u16,
    #[arg(long, default_value_t=2, value_parser=clap::value_parser!(u16).range(1..=2))]
    threads: u16,
    /// Original wall deadline per worker, never enlarged by pauses or subsequent cycles.
    #[arg(long, default_value_t=600, value_parser=clap::value_parser!(u16).range(1..=600))]
    max_seconds: u16,
    /// Limit new cycle attempts, then drain publications for at most one max-seconds window.
    /// Omitted keeps watching until owner cancellation.
    #[arg(long, value_parser=clap::value_parser!(u16).range(1..=256))]
    max_cycles: Option<u16>,
    #[arg(long, default_value_t=60, value_parser=clap::value_parser!(u16).range(1..=3600))]
    poll_seconds: u16,
    /// Explicitly allow more training on an unchanged source; otherwise require a newer revision.
    #[arg(long)]
    repeat_sources: bool,
    /// Enable automatic publication under this owner-local adapter name.
    #[arg(long, value_parser=content::parse_content_name, requires_all=["publication_key","identity","passphrase_file","publish_cache"])]
    publish_name: Option<String>,
    #[arg(long, value_parser=content::parse_publisher_key, requires="publish_name")]
    publication_key: Option<VerifyingKey>,
    /// Existing encrypted owner identity; never generated by the loop.
    #[arg(long, requires = "publish_name")]
    identity: Option<PathBuf>,
    /// Explicit private passphrase file; background execution never prompts interactively.
    #[arg(long, requires = "publish_name")]
    passphrase_file: Option<PathBuf>,
    /// Existing owner-owned cache for new signed publications, separate from the agent cache.
    #[arg(long, requires = "publish_name")]
    publish_cache: Option<PathBuf>,
    /// Existing private directory for owner-approved serving snapshots; never enables a broker itself.
    #[arg(long)]
    serving_directory: Option<PathBuf>,
    #[arg(long, default_value_t=1, value_parser=clap::value_parser!(u64).range(1..))]
    first_publication_revision: u64,
    /// Explicitly start the persistent background service; default only previews its enrollment.
    #[arg(long)]
    execute: bool,
    #[command(flatten)]
    limits: Limits,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct Plan {
    version: u32,
    sources: Vec<Source>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    catalogs: Vec<Source>,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct Source {
    publisher_key: String,
    name: String,
    #[serde(default)]
    min_revision: Option<u64>,
    #[serde(default)]
    manifest_id: Option<String>,
}

impl Source {
    fn key(&self) -> Result<VerifyingKey> {
        content::parse_publisher_key(&self.publisher_key).map_err(anyhow::Error::msg)
    }
    fn manifest(&self) -> Result<Option<[u8; 32]>> {
        self.manifest_id
            .as_ref()
            .map(|value| {
                ensure!(super::is_hex(value, 64), "train_loop_manifest_id");
                let mut bytes = [0; 32];
                hex::decode_to_slice(value, &mut bytes)?;
                ensure!(bytes != [0; 32], "train_loop_manifest_id");
                Ok(bytes)
            })
            .transpose()
    }
}

#[derive(Serialize, Deserialize, Default)]
#[serde(deny_unknown_fields)]
struct SourceProgress {
    revision: Option<u64>,
    next_attempt: u64,
}

#[derive(Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
enum Phase {
    Running,
    Evaluating,
    Trained,
    PublishPending,
    Complete,
    Failed,
    PublicationExpired,
    Rejected,
}

#[derive(Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct Cycle {
    sequence: u64,
    source: usize,
    phase: Phase,
    snapshot: Option<Snapshot>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    training: Option<Snapshot>,
    #[serde(default)]
    publication: Option<Value>,
    next_publication_attempt: u64,
}

#[derive(Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct State {
    version: u32,
    next_sequence: u64,
    cursor: usize,
    completed: u64,
    promoted: u64,
    rejected: u64,
    latest: Option<u64>,
    sources: Vec<SourceProgress>,
    cycles: Vec<Cycle>,
    garbage: Vec<u64>,
    seed: Option<Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    validation: Option<Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    catalog: Option<catalogs::Registry>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    peer_updates: Option<peer_updates::Registry>,
}

impl State {
    fn new(count: usize) -> Self {
        Self {
            version: 2,
            next_sequence: 1,
            cursor: 0,
            completed: 0,
            promoted: 0,
            rejected: 0,
            latest: None,
            sources: (0..count).map(|_| SourceProgress::default()).collect(),
            cycles: Vec::new(),
            garbage: Vec::new(),
            seed: None,
            validation: None,
            catalog: None,
            peer_updates: None,
        }
    }
    fn select(&self, plan: &Plan, repeat: bool, time: u64) -> Option<usize> {
        (0..plan.sources.len())
            .map(|offset| (self.cursor + offset) % plan.sources.len())
            .find(|index| {
                let progress = &self.sources[*index];
                progress.next_attempt <= time
                    && self.catalog.as_ref().is_none_or(|registry| {
                        registry.eligible(registry.static_count(), *index, time)
                    })
                    && (repeat
                        || progress.revision.is_none()
                        || plan.sources[*index].manifest_id.is_none()
                        || plan.sources[*index]
                            .min_revision
                            .zip(progress.revision)
                            .is_some_and(|(offered, completed)| offered > completed))
                    && (repeat || progress.revision != Some(u64::MAX))
            })
    }
}

struct Activity {
    receiver: watch::Receiver<bool>,
    listener: tokio::task::JoinHandle<()>,
}
impl Activity {
    fn new() -> Result<Self> {
        use tokio::signal::unix::{SignalKind, signal};
        let mut interrupt = signal(SignalKind::interrupt())?;
        let mut terminate = signal(SignalKind::terminate())?;
        let (sender, receiver) = watch::channel(true);
        let listener = tokio::spawn(async move {
            tokio::select! { _=interrupt.recv()=>{}, _=terminate.recv()=>{} }
            let _ = sender.send(false);
        });
        Ok(Self { receiver, listener })
    }
}
impl Drop for Activity {
    fn drop(&mut self) {
        self.listener.abort();
    }
}

fn active(activity: &watch::Receiver<bool>) -> bool {
    *activity.borrow() && activity.has_changed().is_ok()
}
fn now() -> Result<u64> {
    Ok(SystemTime::now().duration_since(UNIX_EPOCH)?.as_secs())
}

fn enrollment(args: &Options) -> Result<(Plan, Value)> {
    let plan: Plan = serde_json::from_slice(&read_file(&args.plan, 64 * 1024)?)?;
    ensure!(
        (plan.version == 1
            && plan.catalogs.is_empty()
            && (1..=MAX_SOURCES).contains(&plan.sources.len()))
            || (plan.version == 2
                && (1..=16).contains(&plan.catalogs.len())
                && plan.sources.len() < MAX_SOURCES),
        "train_loop_sources"
    );
    let mut distinct = BTreeSet::new();
    for source in &plan.sources {
        let key = source.key()?;
        source.manifest()?;
        content::parse_content_name(&source.name).map_err(anyhow::Error::msg)?;
        ensure!(
            source.min_revision != Some(0)
                && distinct.insert((key.to_bytes(), source.name.clone())),
            "train_loop_duplicate_source"
        );
    }
    let mut feeds = BTreeSet::new();
    for catalog in &plan.catalogs {
        let key = catalog.key()?;
        catalog.manifest()?;
        content::parse_content_name(&catalog.name).map_err(anyhow::Error::msg)?;
        ensure!(
            catalog.min_revision != Some(0)
                && feeds.insert((key.to_bytes(), catalog.name.clone()))
                && !distinct.contains(&(key.to_bytes(), catalog.name.clone())),
            "train_loop_catalog_identity"
        );
    }
    for path in [
        &args.directory,
        &args.runtime_root,
        &args.model_root,
        &args.cache,
    ]
    .into_iter()
    .chain(args.adapter_root.iter())
    .chain(args.identity.iter())
    .chain(args.passphrase_file.iter())
    .chain(args.publish_cache.iter())
    .chain(args.serving_directory.iter())
    {
        ensure!(path.is_absolute(), "train_loop_absolute_paths");
        if path != &args.directory {
            ensure!(
                !path.starts_with(&args.directory) && !args.directory.starts_with(path),
                "train_loop_directory_overlap"
            );
        }
    }
    let mut selection = json!({"version":1,"sources":plan.sources,"runtime_root":args.runtime_root,"model_root":args.model_root,
        "cache":args.cache,"initial_adapter_root":args.adapter_root,"steps":args.steps,"threads":args.threads,
        "max_worker_seconds":args.max_seconds,"repeat_sources":args.repeat_sources,"limits":args.limits.configuration(),
        "publish_name":args.publish_name,"publication_key":args.publication_key.map(|key|hex::encode(key.as_bytes())),
        "identity":args.identity,"passphrase_file":args.passphrase_file,"publish_cache":args.publish_cache,
        "first_publication_revision":args.first_publication_revision,"seed":seed::selection(args)?,"source_choice_uses_cache_inventory":false,
        "quality_policy":"source-heldout-loss-v1",
        "private_data_supported":false,"code_or_model_downloads":false,"automatic_model_quality_claimed":false});
    if let Some(directory) = &args.serving_directory {
        for other in [&args.runtime_root, &args.model_root, &args.cache]
            .into_iter()
            .chain(args.publish_cache.iter())
        {
            ensure!(
                !directory.starts_with(other) && !other.starts_with(directory),
                "train_loop_serving_directory_overlap"
            );
        }
        selection["serving_directory"] = serde_json::to_value(directory)?;
    }
    if !plan.catalogs.is_empty() {
        selection["catalogs"] = serde_json::to_value(&plan.catalogs)?;
        selection["source_discovery"] = json!("signed-same-publisher-catalogs-v1");
        selection["maximum_remembered_sources"] = json!(MAX_SOURCES);
    }
    if let Some(peers) = peer_updates::selection(args)? {
        ensure!(
            args.validation_source.is_some(),
            "train_loop_peer_validation_required"
        );
        selection["peer_updates"] = peers;
    }
    if let Some(validation) = validation::selection(args)? {
        for source in &plan.sources {
            ensure!(
                (source.key()? != validation.key()? || source.name != validation.name)
                    && (source.manifest()?.is_none()
                        || source.manifest()? != validation.manifest()?),
                "train_loop_validation_source_must_differ"
            );
        }
        selection["validation_source"] = serde_json::to_value(validation)?;
        selection["quality_policy"] = json!("source-and-second-source-loss-v1");
    }
    Ok((plan, selection))
}

#[allow(clippy::too_many_lines)]
pub(super) async fn run(args: &Options, socket: &Path) -> Result<()> {
    let (plan, selection) = enrollment(args)?;
    if !args.execute {
        println!(
            "{}",
            json!({"operation":"compute_train_loop_plan","execute":false,"selection":selection,
            "resume":args.resume,"max_cycles_this_invocation":args.max_cycles,"network_retrieval":false,"training_executed":false})
        );
        return Ok(());
    }
    ensure!(
        !nix::unistd::geteuid().is_root(),
        "compute_unprivileged_user_required"
    );
    private_directory(&args.runtime_root)?;
    private_directory(&args.model_root)?;
    if let Some(root) = &args.adapter_root {
        private_directory(root)?;
    }
    if let Some(root) = &args.publish_cache {
        private_directory(root)?;
    }
    let store = Store::open(&args.directory, &selection, args.resume)?;
    let mut serving = serving::Serving::open(args, &selection)?;
    let mut state: State = store
        .load_state()?
        .map(serde_json::from_value)
        .transpose()?
        .unwrap_or_else(|| State::new(plan.sources.len()));
    let mut pool = restore_source_pool(&plan, &mut state)?;
    recover(&store, &mut state, pool.sources.len())?;
    let activity = Activity::new()?;
    prepare_inputs(
        args,
        socket,
        &selection,
        &store,
        &mut state,
        &activity.receiver,
    )
    .await?;
    checked_integrity_recovery(
        peer_updates::restore(args, &store, &mut state, &selection),
        &mut serving,
    )?;
    if let Some(sequence) = state
        .cycles
        .iter()
        .find(|cycle| cycle.phase == Phase::Evaluating)
        .map(|cycle| cycle.sequence)
    {
        finish_cycle(args, &store, &mut state, sequence, &activity.receiver).await?;
    }
    reconcile_selected_adapter(args, &store, &mut state, &mut serving)?;
    let mut budget = Budget::new();
    let mut attempts = 0_u64;
    let mut publication_drain = None;
    while active(&activity.receiver) {
        if args
            .max_cycles
            .is_some_and(|maximum| attempts >= u64::from(maximum))
        {
            publication_drain = Some(
                publication::drain(args, socket, &store, &mut state, &activity.receiver).await?,
            );
            break;
        }
        publication::pending(args, socket, &store, &mut state, &activity.receiver).await?;
        if budget.sample() == Decision::Run {
            if refresh_catalogs(args, socket, &plan, &store, &mut state, &activity.receiver).await?
            {
                pool = source_pool(&plan, &state);
            }
            // Local integrity recovery is not driven by a failed retrieval or a
            // comparison result. It precedes selecting either job's warmstart.
            reconcile_selected_adapter(args, &store, &mut state, &mut serving)?;
            peer_updates::tick(args, socket, &pool, &store, &mut state, &activity.receiver).await?;
            reconcile_selected_adapter(args, &store, &mut state, &mut serving)?;
            if let Some(source) = state.select(&pool, args.repeat_sources, now()?) {
                if make_room(&store, &mut state)? {
                    reconcile_selected_adapter(args, &store, &mut state, &mut serving)?;
                    attempt(
                        args,
                        socket,
                        &pool,
                        &store,
                        &mut state,
                        source,
                        &activity.receiver,
                    )
                    .await?;
                    reconcile_selected_adapter(args, &store, &mut state, &mut serving)?;
                    attempts = attempts
                        .checked_add(1)
                        .context("train_loop_attempt_counter")?;
                    continue;
                }
            }
        }
        let mut receiver = activity.receiver.clone();
        tokio::select! { _=receiver.changed()=>{}, ()=tokio::time::sleep(Duration::from_millis(250))=>{} }
    }
    store.save_state(&serde_json::to_value(&state)?)?;
    println!(
        "{}",
        json!({"operation":"compute_train_loop","completed_cycles":state.completed,
        "promoted_cycles":state.promoted,"rejected_cycles":state.rejected,"latest_approved_sequence":state.latest,
        "quality_policy":selection["quality_policy"],"independent_quality_benchmark":false,
        "attempts_this_invocation":attempts,"owner_cancelled":!active(&activity.receiver),
        "catalog_source_discovery":state.catalog.is_some(),"remembered_sources":state.sources.len(),
        "peer_update_channels_enabled":state.peer_updates.is_some(),
        "pending_publications":state.cycles.iter().filter(|cycle|matches!(cycle.phase,Phase::Trained|Phase::PublishPending)).count(),
        "publication_drain":publication_drain,"publication_drain_seconds":publication_drain.map(|_|args.max_seconds),
        "private_data_supported":false,"full_b05_claimed":false})
    );
    Ok(())
}

fn reconcile_selected_adapter(
    args: &Options,
    store: &Store,
    state: &mut State,
    serving: &mut Option<serving::Serving>,
) -> Result<()> {
    let recovered =
        checked_integrity_recovery(peer_updates::recover_active(args, store, state), serving)?;
    if let Some(serving) = serving {
        serving.reconcile(args, store, state)?;
    }
    if recovered {
        // A local byte-integrity failure does not establish publisher malice.
        eprintln!("compute loop_event=active_adapter_predecessor_restored");
    }
    Ok(())
}

fn checked_integrity_recovery<T>(
    result: Result<T>,
    serving: &mut Option<serving::Serving>,
) -> Result<T> {
    if result
        .as_ref()
        .err()
        .is_some_and(peer_updates::recovery_blocked)
    {
        if let Some(serving) = serving {
            serving.withdraw()?;
        }
        eprintln!("compute loop_event=active_adapter_recovery_blocked");
    }
    result
}

fn restore_source_pool(base: &Plan, state: &mut State) -> Result<Plan> {
    if state.catalog.is_none() && !base.catalogs.is_empty() {
        ensure!(
            state.next_sequence == 1 && state.cycles.is_empty(),
            "train_loop_missing_catalog_state"
        );
        state.catalog = Some(catalogs::Registry::new(base)?);
    }
    ensure!(
        state.catalog.is_some() != base.catalogs.is_empty(),
        "train_loop_unrequested_catalog_state"
    );
    if let Some(registry) = &state.catalog {
        registry.validate(base, now()?)?;
    }
    Ok(source_pool(base, state))
}

fn source_pool(base: &Plan, state: &State) -> Plan {
    Plan {
        version: base.version,
        sources: state
            .catalog
            .as_ref()
            .map_or_else(|| base.sources.clone(), |registry| registry.sources(base)),
        catalogs: base.catalogs.clone(),
    }
}

async fn refresh_catalogs(
    args: &Options,
    socket: &Path,
    base: &Plan,
    store: &Store,
    state: &mut State,
    activity: &watch::Receiver<bool>,
) -> Result<bool> {
    let Some(registry) = state.catalog.as_mut() else {
        return Ok(false);
    };
    if !registry
        .refresh_one(args, socket, base, store, activity)
        .await?
    {
        return Ok(false);
    }
    let count = registry.sources(base).len();
    ensure!(
        count >= state.sources.len() && count <= MAX_SOURCES,
        "train_loop_catalog_slot_count"
    );
    state.sources.resize_with(count, SourceProgress::default);
    store.save_state(&serde_json::to_value(state)?)?;
    Ok(true)
}

async fn prepare_inputs(
    args: &Options,
    socket: &Path,
    selection: &Value,
    store: &Store,
    state: &mut State,
    activity: &watch::Receiver<bool>,
) -> Result<()> {
    seed::prepare(args, socket, selection, store, state, activity).await?;
    validation::prepare(args, socket, selection, store, state, activity).await
}

fn recover(store: &Store, state: &mut State, count: usize) -> Result<()> {
    ensure!(
        state.version == 2
            && state.next_sequence > 0
            && state.promoted.checked_add(state.rejected) == Some(state.completed)
            && state.completed < state.next_sequence
            && (state.latest.is_some() == (state.promoted > 0))
            && state.sources.len() == count
            && ((count == 0 && state.cursor == 0) || state.cursor < count)
            && state.cycles.len() <= RETAINED_CYCLES
            && state.garbage.len() <= RETAINED_CYCLES,
        "train_loop_state"
    );
    let mut distinct = BTreeSet::new();
    let mut evaluating = 0;
    for sequence in &state.garbage {
        ensure!(
            *sequence > 0
                && *sequence < state.next_sequence
                && Some(*sequence) != state.latest
                && distinct.insert(*sequence)
                && !state.cycles.iter().any(|cycle| cycle.sequence == *sequence),
            "train_loop_garbage_state"
        );
        store.prune_sequence(*sequence)?;
    }
    state.garbage.clear();
    for cycle in &mut state.cycles {
        ensure!(
            cycle.source < count
                && cycle.sequence > 0
                && cycle.sequence < state.next_sequence
                && distinct.insert(cycle.sequence),
            "train_loop_cycle_state"
        );
        if cycle.phase == Phase::Running {
            cycle.phase = Phase::Failed;
        }
        if cycle.phase == Phase::Evaluating {
            evaluating += 1;
            ensure!(
                evaluating == 1
                    && cycle.sequence.checked_add(1) == Some(state.next_sequence)
                    && cycle.publication.is_none(),
                "train_loop_pending_evaluation_state"
            );
            store.validate_training(
                cycle.sequence,
                cycle
                    .training
                    .as_ref()
                    .context("train_loop_training_checkpoint_missing")?,
            )?;
        }
        if let Some(snapshot) = &cycle.snapshot {
            store.validate_snapshot(cycle.sequence, snapshot)?;
            let decision = evaluation::verify(store, cycle.sequence)?;
            ensure!(
                decision.approved == (cycle.phase != Phase::Rejected)
                    && decision.has_validation() == state.validation.is_some()
                    && (cycle.phase != Phase::Rejected || cycle.publication.is_none()),
                "train_loop_evaluation_phase_mismatch"
            );
        }
        ensure!(
            cycle.snapshot.is_some()
                != matches!(
                    cycle.phase,
                    Phase::Running | Phase::Failed | Phase::Evaluating
                ),
            "train_loop_snapshot_required"
        );
    }
    if let Some(latest) = state.latest {
        ensure!(
            state.cycles.iter().any(|cycle| cycle.sequence == latest
                && cycle.snapshot.is_some()
                && cycle.phase != Phase::Rejected),
            "train_loop_latest_missing"
        );
    }
    store.save_state(&serde_json::to_value(state)?)
}

fn make_room(store: &Store, state: &mut State) -> Result<bool> {
    if state.cycles.len() < RETAINED_CYCLES {
        return Ok(true);
    }
    let obsolete = state.cycles.iter().position(|cycle| {
        Some(cycle.sequence) != state.latest
            && matches!(
                cycle.phase,
                Phase::Complete | Phase::Failed | Phase::PublicationExpired | Phase::Rejected
            )
    });
    let Some(index) = obsolete else {
        return Ok(false);
    };
    let sequence = state.cycles[index].sequence;
    // No active worker or unpublished update is selected here. Only exact owned cycle
    // directories are pruned; the current warmstart and failed handoffs stay available.
    state.cycles.remove(index);
    state.garbage.push(sequence);
    // Save the exact disposable target before removing its files. A restart can
    // idempotently finish this cleanup instead of expecting a deleted warmstart.
    store.save_state(&serde_json::to_value(&*state)?)?;
    store.prune_sequence(sequence)?;
    state.garbage.clear();
    store.save_state(&serde_json::to_value(state)?)?;
    Ok(true)
}

async fn attempt(
    args: &Options,
    socket: &Path,
    plan: &Plan,
    store: &Store,
    state: &mut State,
    index: usize,
    activity: &watch::Receiver<bool>,
) -> Result<()> {
    if !active(activity) {
        return Ok(());
    }
    let source = &plan.sources[index];
    let sequence = state.next_sequence;
    let minimum = required_revision(source, &state.sources[index], args.repeat_sources)?;
    let current = current_adapter(args, store, state)?;
    let mut options = cycle_options(
        args,
        source,
        store.cycle_path(sequence)?,
        minimum,
        current.adapter_root,
    )?;
    if current.origin["kind"] == "peer_update" {
        options.peer_predecessor = Some(current.origin);
    }
    if let Some(registry) = &state.catalog {
        options.source_catalog = registry.proof_for(plan, index);
    }
    state.next_sequence = sequence
        .checked_add(1)
        .context("train_loop_sequence_exhausted")?;
    state.cursor = (index + 1) % plan.sources.len();
    state.sources[index].next_attempt = now()?.saturating_add(u64::from(args.poll_seconds));
    state.cycles.push(Cycle {
        sequence,
        source: index,
        phase: Phase::Running,
        snapshot: None,
        training: None,
        publication: None,
        next_publication_attempt: 0,
    });
    store.save_state(&serde_json::to_value(&*state)?)?;
    // Do not select/drop this future on cancellation: the model supervisor must reap.
    let validation_data = validation::data(args, state)?;
    let result = train_cycle::execute_cycle_guarded(
        &options,
        socket,
        activity.clone(),
        validation_data.as_deref(),
    )
    .await;
    if let Err(error) = &result {
        state
            .cycles
            .last_mut()
            .context("train_loop_cycle_missing")?
            .phase = Phase::Failed;
        // Never format the arbitrary error chain: it may contain source text or
        // paths. The stage is compiled context, not extracted from error text.
        eprintln!(
            "compute loop_event=cycle_failed stage={}",
            train_cycle::failure_stage(error)
        );
        if error
            .downcast_ref::<super::supervise::WorkerFailure>()
            .is_some()
        {
            let (_, code) = super::broker::execution_failure_class(error);
            eprintln!("compute loop_worker_failure={code}");
        }
        if let Some(startup) = error.downcast_ref::<super::supervise::StartupFailure>() {
            eprintln!(
                "compute loop_startup_failure exit_code={} signal={} stderr_class={} stderr_bytes={}",
                startup.exit_code, startup.signal, startup.stderr_class, startup.stderr_bytes
            );
        }
        if let Some(io) = error
            .chain()
            .find_map(|cause| cause.downcast_ref::<std::io::Error>())
        {
            eprintln!(
                "compute loop_io_failure kind={:?} errno={}",
                io.kind(),
                io.raw_os_error().unwrap_or(-1)
            );
        }
    } else {
        let training = store.snapshot_training(sequence)?;
        let cycle = state
            .cycles
            .last_mut()
            .context("train_loop_cycle_missing")?;
        cycle.training = Some(training);
        cycle.phase = Phase::Evaluating;
        store.save_state(&serde_json::to_value(&*state)?)?;
        finish_cycle(args, store, state, sequence, activity).await?;
    }
    store.save_state(&serde_json::to_value(&*state)?)?;
    println!(
        "{}",
        json!({"operation":"compute_train_loop_cycle","sequence":sequence,"source_index":index,
        "completed":result.is_ok(),"approved":state.cycles.last().filter(|cycle|cycle.snapshot.is_some()).map(|cycle|cycle.phase!=Phase::Rejected),
        "latest_approved_sequence":state.latest,"quality_policy":if state.validation.is_some(){"source-and-second-source-loss-v1"}else{"source-heldout-loss-v1"},
        "total_completed":state.completed,"selection_used_cache_inventory":false})
    );
    Ok(())
}

struct CurrentAdapter {
    adapter_root: Option<PathBuf>,
    origin: Value,
}

fn current_adapter(args: &Options, store: &Store, state: &State) -> Result<CurrentAdapter> {
    if let Some(registry) = &state.peer_updates {
        if let Some(peer) = peer_updates::active(args, registry, state.latest)? {
            return Ok(CurrentAdapter {
                adapter_root: Some(peer.adapter_root),
                origin: peer.origin,
            });
        }
    }
    if let Some(previous) = state.latest {
        let cycle = state
            .cycles
            .iter()
            .find(|cycle| cycle.sequence == previous)
            .context("train_loop_latest_missing")?;
        store.validate_snapshot(
            previous,
            cycle
                .snapshot
                .as_ref()
                .context("train_loop_latest_snapshot")?,
        )?;
        Ok(CurrentAdapter {
            adapter_root: Some(store.cycle_path(previous)?.join("training/adapter")),
            origin: json!({"kind":"local_cycle","sequence":previous}),
        })
    } else {
        let adapter_root = seed::adapter(args, state)?;
        let kind = if state.seed.is_some() {
            "seed_import"
        } else if adapter_root.is_some() {
            "configured_adapter"
        } else {
            "pinned_base"
        };
        Ok(CurrentAdapter {
            adapter_root,
            origin: json!({"kind":kind}),
        })
    }
}

fn cycle_options(
    args: &Options,
    source: &Source,
    output: PathBuf,
    minimum: Option<u64>,
    adapter: Option<PathBuf>,
) -> Result<train_cycle::Options> {
    Ok(train_cycle::Options {
        publisher_key: source.key()?,
        dataset_name: source.name.clone(),
        dataset_manifest_id: source.manifest()?,
        source_catalog: None,
        peer_predecessor: None,
        min_revision: minimum,
        cache: args.cache.clone(),
        reuse_cache: true,
        runtime_root: args.runtime_root.clone(),
        model_root: args.model_root.clone(),
        adapter_root: adapter,
        output,
        steps: args.steps,
        threads: args.threads,
        max_seconds: args.max_seconds,
        spare_capacity: true,
        execute: true,
        limits: args.limits.clone(),
    })
}

async fn finish_cycle(
    args: &Options,
    store: &Store,
    state: &mut State,
    sequence: u64,
    activity: &watch::Receiver<bool>,
) -> Result<()> {
    ensure!(
        active(activity),
        "train_loop_evaluation_cancelled_training_retained"
    );
    let cycle = state.cycles.last().context("train_loop_cycle_missing")?;
    ensure!(
        cycle.sequence == sequence && cycle.phase == Phase::Evaluating,
        "train_loop_pending_evaluation_state"
    );
    store.validate_training(
        sequence,
        cycle
            .training
            .as_ref()
            .context("train_loop_training_checkpoint_missing")?,
    )?;
    if state.validation.is_some() {
        validation::assess(args, store, state, sequence, activity).await?;
    }
    qualify_cycle(store, state, sequence, args.publish_name.is_some())?;
    store.save_state(&serde_json::to_value(state)?)
}

fn qualify_cycle(
    store: &Store,
    state: &mut State,
    sequence: u64,
    publish: bool,
) -> Result<evaluation::Record> {
    let root = store.cycle_path(sequence)?;
    let selection = store.read_cycle_json(sequence, "selection.json")?;
    let publisher = content::parse_publisher_key(
        selection["publisher_key"]
            .as_str()
            .context("train_loop_cycle_publisher")?,
    )
    .map_err(anyhow::Error::msg)?;
    let adapter: Option<PathBuf> = serde_json::from_value(selection["adapter_root"].clone())?;
    let manifest = SignedManifest::decode(&read_file(&root.join("dataset.manifest"), 64 * 1024)?)?;
    let verified = manifest.verify(&publisher, now()?)?;
    let decision = if root.join("evaluation.json").try_exists()? {
        evaluation::verify(store, sequence)?
    } else {
        let decision = evaluation::assess(store, sequence, state.latest, adapter.as_deref())?;
        store.write_cycle_json(
            sequence,
            "evaluation.json",
            &serde_json::to_value(&decision)?,
        )?;
        decision
    };
    ensure!(
        decision.has_validation() == state.validation.is_some(),
        "train_loop_validation_required"
    );
    select_successor(
        state,
        store.snapshot_cycle(sequence)?,
        verified.metadata().revision,
        &decision,
        publish,
    )?;
    Ok(decision)
}

/// Technical completion is separate from promotion. A rejected candidate never
/// replaces the warmstart, enters the publication queue, or retries the same
/// completed source revision by accident; it remains bounded and reclaimable.
fn select_successor(
    state: &mut State,
    snapshot: Snapshot,
    revision: u64,
    decision: &evaluation::Record,
    publish: bool,
) -> Result<()> {
    ensure!(
        decision.predecessor == state.latest,
        "train_loop_evaluation_predecessor"
    );
    let completed = state
        .completed
        .checked_add(1)
        .context("train_loop_completed_exhausted")?;
    let promoted = state
        .promoted
        .checked_add(u64::from(decision.approved))
        .context("train_loop_promoted_exhausted")?;
    let rejected = state
        .rejected
        .checked_add(u64::from(!decision.approved))
        .context("train_loop_rejected_exhausted")?;
    let cycle = state
        .cycles
        .last_mut()
        .context("train_loop_cycle_missing")?;
    ensure!(
        decision.sequence == cycle.sequence
            && matches!(cycle.phase, Phase::Running | Phase::Evaluating),
        "train_loop_evaluation_cycle"
    );
    state.sources[cycle.source].revision = Some(revision);
    cycle.snapshot = Some(snapshot);
    cycle.training = None;
    cycle.phase = if !decision.approved {
        Phase::Rejected
    } else if publish {
        Phase::Trained
    } else {
        Phase::Complete
    };
    if decision.approved {
        state.latest = Some(cycle.sequence);
        if let Some(registry) = &mut state.peer_updates {
            peer_updates::clear_active(registry);
        }
    }
    state.completed = completed;
    state.promoted = promoted;
    state.rejected = rejected;
    Ok(())
}

fn required_revision(
    source: &Source,
    progress: &SourceProgress,
    repeat: bool,
) -> Result<Option<u64>> {
    match progress.revision.filter(|_| !repeat) {
        Some(previous) => Ok(Some(
            source.min_revision.unwrap_or(1).max(
                previous
                    .checked_add(1)
                    .context("train_loop_revision_exhausted")?,
            ),
        )),
        None => Ok(source.min_revision),
    }
}
