use prost::Message;
use sha2::{Digest, Sha256};
use thiserror::Error;
use tokio::io::{AsyncRead, AsyncReadExt};
use zeroize::{Zeroize, ZeroizeOnDrop};

use crate::NATIVE_API_VERSION;

/// Domain separating response request-correlation digests from every other hash.
pub const NATIVE_REQUEST_DIGEST_DOMAIN: &[u8] = b"VOLPAROSSA-MPQUIC-REQUEST-V6\0";

const NATIVE_INSTANCE_ID_LEN: usize = 32;
const SIGNED_ID_LEN: usize = 16;
const SHA256_LEN: usize = 32;
const NATIVE_ROUTE_AUTH_COMMITMENT_DOMAIN: &[u8] = b"VOLPAROSSA-NATIVE-ROUTE-AUTH-COMMITMENT-V4\0";

/// Hard maximum for one local native-control frame.
pub const MAX_CONTROL_FRAME: usize = 1024 * 1024;

/// Hard maximum for one complete inner IPv4/IPv6 datagram.
pub const MAX_INNER_PACKET: usize = 65_535;

/// Largest valid RFC 9484 context identifier (a 62-bit integer).
pub const MAX_MASQUE_CONTEXT_ID: u64 = (1_u64 << 62) - 1;

/// Exact unpadded base64url length of one 256-bit per-route mqvpn credential.
///
/// Validation here proves only canonical syntax and length; the credential generator is
/// responsible for supplying 256 bits of entropy.
pub const AUTH_SECRET_LEN: usize = 43;

/// Backwards source-compatible name for the exact credential bound.
pub const MAX_AUTH_SECRET: usize = AUTH_SECRET_LEN;

/// Maximum RFC DNS name length accepted for TLS server-name verification.
pub const MAX_TLS_SERVER_NAME: usize = 253;

/// Maximum bounded in-memory server certificate chain accepted by the patched mqvpn API.
pub const MAX_TLS_CERTIFICATE_PEM: usize = 64 * 1024;

/// Maximum bounded in-memory server private key accepted by the patched mqvpn API.
pub const MAX_TLS_PRIVATE_KEY_PEM: usize = 16 * 1024;

/// Longest accepted native route authorization window, in milliseconds.
pub const MAX_AUTHORIZATION_FUTURE_MS: u64 = 15 * 60 * 1_000;

/// Versioned request sent from the unprivileged Rust agent to the isolated native process.
#[derive(Clone, PartialEq, Message)]
pub struct NativeRequest {
    /// Must equal [`NATIVE_API_VERSION`].
    #[prost(uint32, tag = "1")]
    pub api_version: u32,
    /// Per-request nonce generated by the agent; echoed in the response.
    #[prost(bytes = "vec", tag = "2")]
    pub request_nonce: Vec<u8>,
    /// Exact process instance selected by preflight; empty only for preflight itself.
    #[prost(bytes = "vec", tag = "3")]
    pub target_native_instance_id: Vec<u8>,
    /// Strict allowlist of native operations.
    #[prost(
        oneof = "native_request::Operation",
        tags = "10, 11, 12, 13, 14, 15, 16, 17, 18"
    )]
    pub operation: Option<native_request::Operation>,
}

/// Native request operation variants.
pub mod native_request {
    use prost::Oneof;

    use super::{
        AddPath, GetStatus, Preflight, ReceiveDatagram, RemovePath, SendDatagram, StartExitSession,
        StartSession, StopSession,
    };

    /// Exactly one typed native operation.
    #[derive(Clone, PartialEq, Oneof)]
    pub enum Operation {
        /// Establishes one outer MASQUE/MPQUIC session without paths yet.
        #[prost(message, tag = "10")]
        StartSession(StartSession),
        /// Adds one WireGuard-bound QUIC path.
        #[prost(message, tag = "11")]
        AddPath(AddPath),
        /// Removes one existing QUIC path.
        #[prost(message, tag = "12")]
        RemovePath(RemovePath),
        /// Passes one already-authorised inner IP datagram to CONNECT-IP.
        #[prost(message, tag = "13")]
        SendDatagram(SendDatagram),
        /// Requests bounded per-path status.
        #[prost(message, tag = "14")]
        GetStatus(GetStatus),
        /// Closes and wipes one native session.
        #[prost(message, tag = "15")]
        StopSession(StopSession),
        /// Polls one bounded reverse inner IP datagram.
        #[prost(message, tag = "16")]
        ReceiveDatagram(ReceiveDatagram),
        /// Authorises one short-lived route on an explicitly enabled exit.
        #[prost(message, tag = "17")]
        StartExitSession(StartExitSession),
        /// Obtains the role and fresh per-start identity of one native process.
        #[prost(message, tag = "18")]
        Preflight(Preflight),
    }
}

/// Requests one role-specific native process identity without authorising a route.
#[derive(Clone, PartialEq, Message)]
pub struct Preflight {
    /// Exact process role expected by this Rust service.
    #[prost(enumeration = "NativeProcessRole", tag = "1")]
    pub expected_role: i32,
}

/// Fixed packaging role of one isolated native process.
#[derive(Clone, Copy, Debug, PartialEq, Eq, prost::Enumeration)]
#[repr(i32)]
pub enum NativeProcessRole {
    /// Invalid proto3 default.
    Unspecified = 0,
    /// Client-side native transport process.
    Client = 1,
    /// Exit-side native transport process.
    Exit = 2,
}

/// Starts a native QUIC session for a pre-authorised route context.
#[derive(Clone, PartialEq, Message, Zeroize, ZeroizeOnDrop)]
pub struct StartSession {
    /// Opaque 16-byte route context ID.
    #[prost(bytes = "vec", tag = "1")]
    pub route_context_id: Vec<u8>,
    /// Exit certificate/SPKI SHA-256 pin.
    #[prost(bytes = "vec", tag = "2")]
    pub exit_spki_sha256: Vec<u8>,
    /// Required data-carrying paths, constrained by transport mode.
    #[prost(uint32, tag = "3")]
    pub minimum_paths: u32,
    /// Independent non-zero MASQUE association context.
    #[prost(uint64, tag = "4")]
    pub masque_context_id: u64,
    /// Explicit transport mode; zero/unknown values are rejected.
    #[prost(enumeration = "TransportMode", tag = "5")]
    pub transport_mode: i32,
    /// Per-route mqvpn credential; never process-global or logged.
    #[prost(bytes = "vec", tag = "6")]
    pub auth_secret: Vec<u8>,
    /// Exact DNS name used for TLS certificate verification on this route.
    #[prost(bytes = "vec", tag = "7")]
    pub tls_server_name: Vec<u8>,
    /// Absolute Unix time in milliseconds; native accepts at most fifteen minutes.
    #[prost(uint64, tag = "8")]
    pub expires_at_ms: u64,
    /// Exact exit-signed reservation identifier.
    #[prost(bytes = "vec", tag = "9")]
    pub reservation_id: Vec<u8>,
    /// Exact exit-signed finalization identifier.
    #[prost(bytes = "vec", tag = "10")]
    pub finalize_id: Vec<u8>,
    /// Exit-signed SHA-256 commitment to [`Self::auth_secret`].
    #[prost(bytes = "vec", tag = "11")]
    pub auth_commitment: Vec<u8>,
    /// Exit-signed SHA-256 digest of the selected leaf certificate.
    #[prost(bytes = "vec", tag = "12")]
    pub certificate_sha256: Vec<u8>,
    /// Exact client native instance bound into the signed reservation.
    #[prost(bytes = "vec", tag = "13")]
    pub client_native_instance_id: Vec<u8>,
    /// Exact exit native instance bound into the signed reservation.
    #[prost(bytes = "vec", tag = "14")]
    pub exit_native_instance_id: Vec<u8>,
}

/// Authorises one short-lived route on an explicitly enabled native exit.
#[derive(Clone, PartialEq, Message, Zeroize, ZeroizeOnDrop)]
pub struct StartExitSession {
    /// Opaque 16-byte route context ID.
    #[prost(bytes = "vec", tag = "1")]
    pub route_context_id: Vec<u8>,
    /// Per-route mqvpn credential; never process-global or logged.
    #[prost(bytes = "vec", tag = "2")]
    pub auth_secret: Vec<u8>,
    /// Absolute Unix time in milliseconds; native accepts at most fifteen minutes.
    #[prost(uint64, tag = "3")]
    pub expires_at_ms: u64,
    /// Required data-carrying paths, constrained by transport mode.
    #[prost(uint32, tag = "4")]
    pub minimum_paths: u32,
    /// Independent non-zero MASQUE association context.
    #[prost(uint64, tag = "5")]
    pub masque_context_id: u64,
    /// Explicit transport mode; zero/unknown values are rejected.
    #[prost(enumeration = "TransportMode", tag = "6")]
    pub transport_mode: i32,
    /// Exact SPKI SHA-256 pin the client must use for this route identity.
    #[prost(bytes = "vec", tag = "7")]
    pub exit_spki_sha256: Vec<u8>,
    /// Expected DNS name the exit backend must bind to the parsed route identity.
    #[prost(bytes = "vec", tag = "8")]
    pub tls_server_name: Vec<u8>,
    /// Non-zero path-local identifier embedded in both overlay addresses.
    #[prost(uint32, tag = "9")]
    pub path_id: u32,
    /// Exact sixteen-byte exit overlay address already bound on the listener descriptor.
    #[prost(bytes = "vec", tag = "10")]
    pub listener_ip: Vec<u8>,
    /// Exact non-zero UDP listener port already bound on the descriptor.
    #[prost(uint32, tag = "11")]
    pub listener_port: u32,
    /// Exact sixteen-byte client overlay address authorised to reach this listener.
    #[prost(bytes = "vec", tag = "12")]
    pub expected_client_ip: Vec<u8>,
    /// Exact client UDP source port authorised for this route.
    #[prost(uint32, tag = "13")]
    pub expected_client_port: u32,
    /// Relay reservation proof hash bound to this exact single path.
    #[prost(bytes = "vec", tag = "14")]
    pub reservation_hash: Vec<u8>,
    /// Bounded in-memory PEM certificate chain; never a pathname.
    #[prost(bytes = "vec", tag = "15")]
    pub tls_certificate_pem: Vec<u8>,
    /// Bounded in-memory PEM private key; never a pathname.
    #[prost(bytes = "vec", tag = "16")]
    pub tls_private_key_pem: Vec<u8>,
    /// Exact exit-signed reservation identifier.
    #[prost(bytes = "vec", tag = "17")]
    pub reservation_id: Vec<u8>,
    /// Exact exit-signed finalization identifier.
    #[prost(bytes = "vec", tag = "18")]
    pub finalize_id: Vec<u8>,
    /// Exit-signed SHA-256 commitment to [`Self::auth_secret`].
    #[prost(bytes = "vec", tag = "19")]
    pub auth_commitment: Vec<u8>,
    /// Exit-signed SHA-256 digest of the selected leaf certificate.
    #[prost(bytes = "vec", tag = "20")]
    pub certificate_sha256: Vec<u8>,
    /// Exact client native instance bound into the signed reservation.
    #[prost(bytes = "vec", tag = "21")]
    pub client_native_instance_id: Vec<u8>,
    /// Exact exit native instance bound into the signed reservation.
    #[prost(bytes = "vec", tag = "22")]
    pub exit_native_instance_id: Vec<u8>,
}

/// Exact native transport shape. No mode permits an implicit downgrade.
#[derive(Clone, Copy, Debug, PartialEq, Eq, prost::Enumeration)]
#[repr(i32)]
pub enum TransportMode {
    /// Invalid proto3 default.
    Unspecified = 0,
    /// Genuine Multipath QUIC with at least two selected paths.
    MultipathQuic = 1,
    /// Protected ordinary QUIC for general UDP with exactly one path.
    SinglePathGeneralUdp = 2,
}

/// Binds one outer QUIC path to one helper-created route-namespace UDP descriptor.
#[derive(Clone, PartialEq, Message)]
pub struct AddPath {
    /// Opaque 16-byte route context ID.
    #[prost(bytes = "vec", tag = "1")]
    pub route_context_id: Vec<u8>,
    /// Non-zero context-local path ID.
    #[prost(uint32, tag = "2")]
    pub path_id: u32,
    /// Exact sixteen-byte client overlay address for this path-specific `/112`.
    #[prost(bytes = "vec", tag = "4")]
    pub local_ip: Vec<u8>,
    /// Exact sixteen-byte exit overlay address in the same path-specific `/112`.
    #[prost(bytes = "vec", tag = "5")]
    pub remote_ip: Vec<u8>,
    /// Exit MPQUIC UDP port.
    #[prost(uint32, tag = "6")]
    pub remote_port: u32,
    /// Relay reservation proof hash bound to this path.
    #[prost(bytes = "vec", tag = "7")]
    pub reservation_hash: Vec<u8>,
    /// Helper-selected non-zero local UDP port already bound on the descriptor.
    #[prost(uint32, tag = "8")]
    pub local_port: u32,
}

/// Removes a native path without accepting arbitrary network identifiers.
#[derive(Clone, PartialEq, Message)]
pub struct RemovePath {
    /// Opaque 16-byte route context ID.
    #[prost(bytes = "vec", tag = "1")]
    pub route_context_id: Vec<u8>,
    /// Existing context-local path ID.
    #[prost(uint32, tag = "2")]
    pub path_id: u32,
}

/// One inner IP datagram previously authorised by Rust policy/session code.
#[derive(Clone, PartialEq, Message)]
pub struct SendDatagram {
    /// Opaque 16-byte route context ID.
    #[prost(bytes = "vec", tag = "1")]
    pub route_context_id: Vec<u8>,
    /// Bounded complete IPv4/IPv6 datagram.
    #[prost(bytes = "vec", tag = "2")]
    pub inner_ip_packet: Vec<u8>,
    /// Exact non-zero MASQUE association context for this session.
    #[prost(uint64, tag = "3")]
    pub masque_context_id: u64,
}

/// Bounded request to poll one reverse inner datagram.
#[derive(Clone, PartialEq, Message)]
pub struct ReceiveDatagram {
    /// Opaque 16-byte route context ID.
    #[prost(bytes = "vec", tag = "1")]
    pub route_context_id: Vec<u8>,
    /// Exact non-zero MASQUE association context for this session.
    #[prost(uint64, tag = "2")]
    pub masque_context_id: u64,
}

/// Status request for one route context.
#[derive(Clone, PartialEq, Message)]
pub struct GetStatus {
    /// Opaque 16-byte route context ID.
    #[prost(bytes = "vec", tag = "1")]
    pub route_context_id: Vec<u8>,
}

/// Stop request for one route context.
#[derive(Clone, PartialEq, Message)]
pub struct StopSession {
    /// Opaque 16-byte route context ID.
    #[prost(bytes = "vec", tag = "1")]
    pub route_context_id: Vec<u8>,
}

/// Versioned response from native process.
#[derive(Clone, PartialEq, Message)]
pub struct NativeResponse {
    /// Native API version.
    #[prost(uint32, tag = "1")]
    pub api_version: u32,
    /// Echoed request nonce.
    #[prost(bytes = "vec", tag = "2")]
    pub request_nonce: Vec<u8>,
    /// Structured result code; zero denotes success.
    #[prost(enumeration = "NativeResultCode", tag = "3")]
    pub result: i32,
    /// Bounded non-sensitive diagnostic code, never arbitrary upstream text.
    #[prost(string, tag = "4")]
    pub diagnostic_code: String,
    /// Per-path metrics when requested.
    #[prost(message, repeated, tag = "5")]
    pub paths: Vec<NativePathStatus>,
    /// One reverse inner datagram, present only for a successful receive poll.
    #[prost(message, optional, tag = "6")]
    pub received_datagram: Option<ReceivedDatagram>,
    /// Current role and per-start identity of the responding native process.
    #[prost(message, optional, tag = "7")]
    pub process_identity: Option<NativeProcessIdentity>,
    /// SHA-256 digest of the exact canonical unframed request.
    #[prost(bytes = "vec", tag = "8")]
    pub request_sha256: Vec<u8>,
    /// Native tunnel parameters returned only by successful client `StartSession`.
    #[prost(message, optional, tag = "9")]
    pub tunnel_assignment: Option<TunnelAssignment>,
}

/// Role and random per-start identity reported by the native process itself.
///
/// This correlates one local process lifetime. It is not binary attestation.
#[derive(Clone, PartialEq, Message)]
pub struct NativeProcessIdentity {
    /// Fixed process role.
    #[prost(enumeration = "NativeProcessRole", tag = "1")]
    pub role: i32,
    /// Fresh non-zero 256-bit identity generated for this process start.
    #[prost(bytes = "vec", tag = "2")]
    pub native_instance_id: Vec<u8>,
}

/// Bounded tunnel parameters allocated by a successful native client session start.
#[derive(Clone, PartialEq, Message)]
pub struct TunnelAssignment {
    /// Assigned client IPv4 address.
    #[prost(bytes = "vec", tag = "1")]
    pub assigned_ipv4: Vec<u8>,
    /// Exact IPv4 prefix length; v6 requires a host route.
    #[prost(uint32, tag = "2")]
    pub assigned_prefix_v4: u32,
    /// Server-side IPv4 address.
    #[prost(bytes = "vec", tag = "3")]
    pub server_ipv4: Vec<u8>,
    /// Exact server IPv4 prefix length; v6 requires a host route.
    #[prost(uint32, tag = "4")]
    pub server_prefix_v4: u32,
    /// Native tunnel MTU.
    #[prost(uint32, tag = "5")]
    pub mtu: u32,
    /// Optional assigned client IPv6 address.
    #[prost(bytes = "vec", tag = "6")]
    pub assigned_ipv6: Vec<u8>,
    /// Zero when IPv6 is absent, otherwise an explicitly bounded prefix.
    #[prost(uint32, tag = "7")]
    pub assigned_prefix_v6: u32,
}

/// Stable structured native result codes.
#[derive(Clone, Copy, Debug, PartialEq, Eq, prost::Enumeration)]
#[repr(i32)]
pub enum NativeResultCode {
    /// Operation completed.
    Ok = 0,
    /// API version is unsupported.
    Version = 1,
    /// Request failed structural validation.
    InvalidRequest = 2,
    /// Session or path does not exist.
    NotFound = 3,
    /// Reservation or policy authorisation is invalid/expired.
    Unauthorised = 4,
    /// Native transport failed without exposing upstream text.
    Transport = 5,
    /// Required explicit path count is unavailable.
    InsufficientPaths = 6,
    /// A receive poll completed without queued data.
    NoDatagram = 7,
    /// Reverse queue limits were exceeded and the session failed closed.
    QueueOverflow = 8,
    /// The selected process lifetime ended; callers must discard route authority.
    StaleInstance = 9,
}

/// Reverse inner IP datagram correlated to its exact native session.
#[derive(Clone, PartialEq, Message, Zeroize, ZeroizeOnDrop)]
pub struct ReceivedDatagram {
    /// Opaque 16-byte route context ID.
    #[prost(bytes = "vec", tag = "1")]
    pub route_context_id: Vec<u8>,
    /// Exact non-zero MASQUE association context.
    #[prost(uint64, tag = "2")]
    pub masque_context_id: u64,
    /// Complete bounded IPv4/IPv6 datagram; wiped when dropped.
    #[prost(bytes = "vec", tag = "3")]
    pub inner_ip_packet: Vec<u8>,
}

impl ReceivedDatagram {
    /// Explicitly wipes packet and correlation material before early discard.
    pub fn wipe(&mut self) {
        self.zeroize();
    }
}

/// Bounded metrics for one genuine native QUIC path.
#[derive(Clone, PartialEq, Message)]
pub struct NativePathStatus {
    /// Context-local path ID.
    #[prost(uint32, tag = "1")]
    pub path_id: u32,
    /// Smoothed RTT in microseconds.
    #[prost(uint64, tag = "2")]
    pub smoothed_rtt_us: u64,
    /// Lost packets since last reset.
    #[prost(uint64, tag = "3")]
    pub packets_lost: u64,
    /// Successfully delivered unique bytes.
    #[prost(uint64, tag = "4")]
    pub delivered_bytes: u64,
    /// Congestion window.
    #[prost(uint64, tag = "5")]
    pub congestion_window_bytes: u64,
    /// Bytes in flight.
    #[prost(uint64, tag = "6")]
    pub bytes_in_flight: u64,
    /// Estimated delivery rate in bits per second.
    #[prost(uint64, tag = "7")]
    pub delivery_rate_bps: u64,
    /// True only after the path was validated and has carried payload.
    #[prost(bool, tag = "8")]
    pub data_carrying: bool,
}

/// Fail-closed frame/validation errors.
#[derive(Debug, Error)]
pub enum ControlError {
    /// Async local socket I/O failed.
    #[error("native control I/O failed: {0}")]
    Io(#[from] std::io::Error),
    /// Protobuf payload is malformed.
    #[error("native control protobuf is malformed: {0}")]
    Decode(#[from] prost::DecodeError),
    /// Frame exceeds the fixed local limit.
    #[error("native control frame exceeds {MAX_CONTROL_FRAME} bytes")]
    TooLarge,
    /// Message violates a structural security rule.
    #[error("invalid native control message: {0}")]
    Invalid(&'static str),
}

/// Encodes and length-prefixes a validated native request.
///
/// # Errors
///
/// Returns an error when request validation fails or the encoded frame exceeds the hard limit.
pub fn encode_request(request: &NativeRequest) -> Result<Vec<u8>, ControlError> {
    validate_request(request)?;
    encode_frame(request)
}

/// Computes the v6 response-correlation digest of one canonical unframed request.
///
/// # Errors
///
/// Returns an error when the request is invalid or its canonical payload exceeds the frame bound.
pub fn request_sha256(request: &NativeRequest) -> Result<[u8; SHA256_LEN], ControlError> {
    validate_request(request)?;
    let payload = zeroize::Zeroizing::new(request.encode_to_vec());
    if payload.is_empty() || payload.len() > MAX_CONTROL_FRAME {
        return Err(ControlError::TooLarge);
    }
    let payload_len = u32::try_from(payload.len()).map_err(|_| ControlError::TooLarge)?;
    let mut hasher = Sha256::new();
    hasher.update(NATIVE_REQUEST_DIGEST_DOMAIN);
    hasher.update(payload_len.to_be_bytes());
    hasher.update(payload.as_slice());
    Ok(hasher.finalize().into())
}

/// Encodes and length-prefixes a validated native response.
///
/// # Errors
///
/// Returns an error when response validation fails or the encoded frame exceeds the hard limit.
pub fn encode_response(response: &NativeResponse) -> Result<Vec<u8>, ControlError> {
    validate_response(response)?;
    encode_frame(response)
}

/// Decodes one already-unframed request payload.
///
/// # Errors
///
/// Returns an error for oversized, malformed, or semantically invalid request bytes.
pub fn decode_request(bytes: &[u8]) -> Result<NativeRequest, ControlError> {
    if bytes.len() > MAX_CONTROL_FRAME {
        return Err(ControlError::TooLarge);
    }
    let request = NativeRequest::decode(bytes)?;
    validate_request(&request)?;
    let canonical = zeroize::Zeroizing::new(request.encode_to_vec());
    if canonical.as_slice() != bytes {
        return Err(ControlError::Invalid("non-canonical request encoding"));
    }
    Ok(request)
}

/// Decodes one already-unframed response payload.
///
/// # Errors
///
/// Returns an error for oversized, malformed, or semantically invalid response bytes.
pub fn decode_response(bytes: &[u8]) -> Result<NativeResponse, ControlError> {
    if bytes.len() > MAX_CONTROL_FRAME {
        return Err(ControlError::TooLarge);
    }
    let response = NativeResponse::decode(bytes)?;
    validate_response(&response)?;
    let canonical = zeroize::Zeroizing::new(response.encode_to_vec());
    if canonical.as_slice() != bytes {
        return Err(ControlError::Invalid("non-canonical response encoding"));
    }
    Ok(response)
}

/// Reads one bounded length-prefixed request.
///
/// # Errors
///
/// Returns an error when the stream cannot be read or its frame is empty, oversized, malformed,
/// or semantically invalid.
pub async fn read_request<R>(reader: &mut R) -> Result<NativeRequest, ControlError>
where
    R: AsyncRead + Unpin,
{
    let mut payload = read_frame(reader).await?;
    let result = decode_request(&payload);
    payload.zeroize();
    result
}

/// Reads one bounded length-prefixed response.
///
/// # Errors
///
/// Returns an error when the stream cannot be read or its frame is empty, oversized, malformed,
/// or semantically invalid.
pub async fn read_response<R>(reader: &mut R) -> Result<NativeResponse, ControlError>
where
    R: AsyncRead + Unpin,
{
    let mut payload = read_frame(reader).await?;
    let result = decode_response(&payload);
    payload.zeroize();
    result
}

fn encode_frame<M: Message>(message: &M) -> Result<Vec<u8>, ControlError> {
    let encoded_len = message.encoded_len();
    if encoded_len > MAX_CONTROL_FRAME {
        return Err(ControlError::TooLarge);
    }
    let length = u32::try_from(encoded_len).map_err(|_| ControlError::TooLarge)?;
    let mut frame = Vec::with_capacity(4 + encoded_len);
    frame.extend_from_slice(&length.to_be_bytes());
    message
        .encode(&mut frame)
        .map_err(|_| ControlError::TooLarge)?;
    Ok(frame)
}

async fn read_frame<R>(reader: &mut R) -> Result<Vec<u8>, ControlError>
where
    R: AsyncRead + Unpin,
{
    let length = reader.read_u32().await?;
    let length = usize::try_from(length).map_err(|_| ControlError::TooLarge)?;
    if length == 0 {
        return Err(ControlError::Invalid("empty frame"));
    }
    if length > MAX_CONTROL_FRAME {
        return Err(ControlError::TooLarge);
    }
    let mut payload = vec![0_u8; length];
    reader.read_exact(&mut payload).await?;
    Ok(payload)
}

fn validate_request(request: &NativeRequest) -> Result<(), ControlError> {
    use native_request::Operation;

    if request.api_version != NATIVE_API_VERSION {
        return Err(ControlError::Invalid("unsupported API version"));
    }
    if request.request_nonce.len() != 16 || request.request_nonce.iter().all(|byte| *byte == 0) {
        return Err(ControlError::Invalid(
            "request nonce must be a non-zero 16-byte value",
        ));
    }
    let operation = request
        .operation
        .as_ref()
        .ok_or(ControlError::Invalid("missing operation"))?;
    if matches!(operation, Operation::Preflight(_)) {
        if !request.target_native_instance_id.is_empty() {
            return Err(ControlError::Invalid(
                "preflight must not target a native process instance",
            ));
        }
    } else {
        validate_native_instance_id(&request.target_native_instance_id)?;
    }
    match operation {
        Operation::Preflight(value) => {
            validate_native_role(value.expected_role)?;
        }
        Operation::StartSession(value) => {
            validate_context(&value.route_context_id)?;
            if value.exit_spki_sha256.len() != 32
                || value.exit_spki_sha256.iter().all(|byte| *byte == 0)
            {
                return Err(ControlError::Invalid(
                    "SPKI pin must be a non-zero 32-byte value",
                ));
            }
            validate_session_shape(
                value.minimum_paths,
                value.masque_context_id,
                value.transport_mode,
            )?;
            validate_auth_secret(&value.auth_secret)?;
            validate_tls_server_name(&value.tls_server_name)?;
            validate_expiry(value.expires_at_ms)?;
            validate_signed_route_fields(
                &value.reservation_id,
                &value.finalize_id,
                &value.auth_secret,
                &value.auth_commitment,
                &value.certificate_sha256,
                &value.client_native_instance_id,
                &value.exit_native_instance_id,
            )?;
            if value.client_native_instance_id != request.target_native_instance_id {
                return Err(ControlError::Invalid(
                    "client start does not target its signed native instance",
                ));
            }
        }
        Operation::StartExitSession(value) => {
            validate_start_exit(value)?;
            if value.exit_native_instance_id != request.target_native_instance_id {
                return Err(ControlError::Invalid(
                    "exit start does not target its signed native instance",
                ));
            }
        }
        Operation::AddPath(value) => {
            validate_add_path(value)?;
        }
        Operation::RemovePath(value) => {
            validate_context(&value.route_context_id)?;
            if value.path_id == 0 || value.path_id > 8 {
                return Err(ControlError::Invalid("invalid path ID"));
            }
        }
        Operation::SendDatagram(value) => {
            validate_context(&value.route_context_id)?;
            validate_masque_context(value.masque_context_id)?;
            validate_ip_packet(&value.inner_ip_packet)?;
        }
        Operation::GetStatus(value) => validate_context(&value.route_context_id)?,
        Operation::StopSession(value) => validate_context(&value.route_context_id)?,
        Operation::ReceiveDatagram(value) => {
            validate_context(&value.route_context_id)?;
            validate_masque_context(value.masque_context_id)?;
        }
    }
    Ok(())
}

fn validate_response(response: &NativeResponse) -> Result<(), ControlError> {
    if response.api_version != NATIVE_API_VERSION
        || response.request_nonce.len() != 16
        || response.request_nonce.iter().all(|byte| *byte == 0)
    {
        return Err(ControlError::Invalid("invalid response version or nonce"));
    }
    let result = NativeResultCode::try_from(response.result)
        .map_err(|_| ControlError::Invalid("unknown native result code"))?;
    let identity = response
        .process_identity
        .as_ref()
        .ok_or(ControlError::Invalid("missing native process identity"))?;
    validate_native_role(identity.role)?;
    validate_native_instance_id(&identity.native_instance_id)?;
    if response.request_sha256.len() != SHA256_LEN {
        return Err(ControlError::Invalid("invalid request digest"));
    }
    if let Some(assignment) = response.tunnel_assignment.as_ref() {
        if result != NativeResultCode::Ok || response.received_datagram.is_some() {
            return Err(ControlError::Invalid(
                "tunnel assignment is inappropriate for this response",
            ));
        }
        validate_tunnel_assignment(assignment)?;
    }
    if response.diagnostic_code.len() > 64
        || !response
            .diagnostic_code
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'_' | b'-'))
    {
        return Err(ControlError::Invalid("invalid diagnostic code"));
    }
    if response.paths.len() > 8 {
        return Err(ControlError::Invalid("too many native path records"));
    }
    let mut seen_path_ids = 0_u16;
    for path in &response.paths {
        if path.path_id == 0 || path.path_id > 8 {
            return Err(ControlError::Invalid("invalid native path ID"));
        }
        let bit = 1_u16 << (path.path_id - 1);
        if seen_path_ids & bit != 0 {
            return Err(ControlError::Invalid("duplicate native path ID"));
        }
        seen_path_ids |= bit;
    }
    if let Some(datagram) = response.received_datagram.as_ref() {
        if result != NativeResultCode::Ok || !response.paths.is_empty() {
            return Err(ControlError::Invalid(
                "datagram is not valid for this response result",
            ));
        }
        validate_context(&datagram.route_context_id)?;
        validate_masque_context(datagram.masque_context_id)?;
        validate_ip_packet(&datagram.inner_ip_packet)?;
    }
    if matches!(
        result,
        NativeResultCode::NoDatagram | NativeResultCode::QueueOverflow
    ) && response.received_datagram.is_some()
    {
        return Err(ControlError::Invalid(
            "empty or overflow response carried a datagram",
        ));
    }
    Ok(())
}

fn validate_native_role(role: i32) -> Result<NativeProcessRole, ControlError> {
    match NativeProcessRole::try_from(role) {
        Ok(NativeProcessRole::Client) => Ok(NativeProcessRole::Client),
        Ok(NativeProcessRole::Exit) => Ok(NativeProcessRole::Exit),
        Ok(NativeProcessRole::Unspecified) | Err(_) => {
            Err(ControlError::Invalid("invalid native process role"))
        }
    }
}

fn validate_native_instance_id(value: &[u8]) -> Result<(), ControlError> {
    validate_nonzero_fixed::<NATIVE_INSTANCE_ID_LEN>(value, "invalid native process instance ID")
}

fn validate_nonzero_fixed<const LENGTH: usize>(
    value: &[u8],
    diagnostic: &'static str,
) -> Result<(), ControlError> {
    if value.len() != LENGTH || value.iter().all(|byte| *byte == 0) {
        return Err(ControlError::Invalid(diagnostic));
    }
    Ok(())
}

#[allow(clippy::too_many_arguments)]
fn validate_signed_route_fields(
    reservation_id: &[u8],
    finalize_id: &[u8],
    auth_secret: &[u8],
    auth_commitment: &[u8],
    certificate_sha256: &[u8],
    client_native_instance_id: &[u8],
    exit_native_instance_id: &[u8],
) -> Result<(), ControlError> {
    validate_nonzero_fixed::<SIGNED_ID_LEN>(reservation_id, "invalid signed reservation ID")?;
    validate_nonzero_fixed::<SIGNED_ID_LEN>(finalize_id, "invalid signed finalize ID")?;
    validate_nonzero_fixed::<SHA256_LEN>(auth_commitment, "invalid authentication commitment")?;
    validate_nonzero_fixed::<SHA256_LEN>(certificate_sha256, "invalid certificate digest")?;
    validate_native_instance_id(client_native_instance_id)?;
    validate_native_instance_id(exit_native_instance_id)?;

    let mut hasher = Sha256::new();
    hasher.update(NATIVE_ROUTE_AUTH_COMMITMENT_DOMAIN);
    hasher.update(auth_secret);
    let expected: [u8; SHA256_LEN] = hasher.finalize().into();
    if auth_commitment != expected {
        return Err(ControlError::Invalid(
            "authentication bearer does not match signed commitment",
        ));
    }
    Ok(())
}

fn validate_tunnel_assignment(value: &TunnelAssignment) -> Result<(), ControlError> {
    if value.assigned_ipv4.len() != 4
        || value.assigned_ipv4.iter().all(|byte| *byte == 0)
        || value.assigned_prefix_v4 != 32
        || value.server_ipv4.len() != 4
        || value.server_ipv4.iter().all(|byte| *byte == 0)
        || value.assigned_ipv4 == value.server_ipv4
        || value.server_prefix_v4 != 32
        || !(1_280..=9_000).contains(&value.mtu)
    {
        return Err(ControlError::Invalid("invalid IPv4 tunnel assignment"));
    }
    if value.assigned_ipv6.is_empty() {
        if value.assigned_prefix_v6 != 0 {
            return Err(ControlError::Invalid("absent IPv6 assignment has a prefix"));
        }
    } else if value.assigned_ipv6.len() != 16
        || value.assigned_ipv6.iter().all(|byte| *byte == 0)
        || !(96..=126).contains(&value.assigned_prefix_v6)
    {
        return Err(ControlError::Invalid("invalid IPv6 tunnel assignment"));
    }
    Ok(())
}

fn validate_session_shape(
    minimum_paths: u32,
    masque_context_id: u64,
    transport_mode: i32,
) -> Result<(), ControlError> {
    validate_masque_context(masque_context_id)?;
    let mode = TransportMode::try_from(transport_mode)
        .map_err(|_| ControlError::Invalid("unknown transport mode"))?;
    match mode {
        TransportMode::MultipathQuic if (2..=8).contains(&minimum_paths) => Ok(()),
        TransportMode::SinglePathGeneralUdp if minimum_paths == 1 => Ok(()),
        TransportMode::Unspecified => Err(ControlError::Invalid("transport mode is required")),
        _ => Err(ControlError::Invalid(
            "path count does not match transport mode",
        )),
    }
}

fn validate_auth_secret(value: &[u8]) -> Result<(), ControlError> {
    if value.len() != AUTH_SECRET_LEN
        || !value
            .iter()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(*byte, b'_' | b'-'))
        || !value
            .last()
            .is_some_and(|byte| b"AEIMQUYcgkosw048".contains(byte))
    {
        return Err(ControlError::Invalid(
            "per-route auth credential must be canonical unpadded base64url for 32 bytes",
        ));
    }
    Ok(())
}

fn validate_tls_server_name(value: &[u8]) -> Result<(), ControlError> {
    if value.is_empty() || value.len() > MAX_TLS_SERVER_NAME {
        return Err(ControlError::Invalid("invalid TLS server name"));
    }
    for label in value.split(|byte| *byte == 46) {
        if label.is_empty()
            || label.len() > 63
            || !label[0].is_ascii_alphanumeric()
            || !label[label.len() - 1].is_ascii_alphanumeric()
            || !label
                .iter()
                .all(|byte| byte.is_ascii_alphanumeric() || *byte == 45)
        {
            return Err(ControlError::Invalid("invalid TLS server name"));
        }
    }
    Ok(())
}

fn validate_expiry(expires_at_ms: u64) -> Result<(), ControlError> {
    if expires_at_ms == 0 {
        return Err(ControlError::Invalid("authorization expiry is required"));
    }
    Ok(())
}

fn validate_context(value: &[u8]) -> Result<(), ControlError> {
    if value.len() != 16 || value.iter().all(|byte| *byte == 0) {
        return Err(ControlError::Invalid(
            "route context ID must be a non-zero 16-byte value",
        ));
    }
    Ok(())
}

pub(crate) fn validate_add_path(value: &AddPath) -> Result<(), ControlError> {
    const OVERLAY_PREFIX: [u8; 6] = [0xfd, 0x76, 0x6f, 0x6c, 0x70, 0x61];

    validate_context(&value.route_context_id)?;
    let valid_overlay = value.local_ip.len() == 16
        && value.remote_ip.len() == 16
        && value.local_ip.starts_with(&OVERLAY_PREFIX)
        && value.remote_ip.starts_with(&OVERLAY_PREFIX)
        && value.local_ip[..14] == value.remote_ip[..14]
        && u16::from_be_bytes([value.local_ip[10], value.local_ip[11]])
            == u16::try_from(value.path_id).unwrap_or(0)
        && u16::from_be_bytes([value.local_ip[14], value.local_ip[15]]) == 1
        && u16::from_be_bytes([value.remote_ip[14], value.remote_ip[15]]) == 4;
    if value.path_id == 0
        || value.path_id > 8
        || !valid_overlay
        || !(1..=65_535).contains(&value.local_port)
        || !(1..=65_535).contains(&value.remote_port)
        || value.reservation_hash.len() != 32
        || value.reservation_hash.iter().all(|byte| *byte == 0)
    {
        return Err(ControlError::Invalid(
            "AddPath must name one canonical client-to-exit overlay path",
        ));
    }
    Ok(())
}

pub(crate) fn validate_start_exit(value: &StartExitSession) -> Result<(), ControlError> {
    validate_context(&value.route_context_id)?;
    validate_session_shape(
        value.minimum_paths,
        value.masque_context_id,
        value.transport_mode,
    )?;
    if !matches!(
        TransportMode::try_from(value.transport_mode),
        Ok(TransportMode::SinglePathGeneralUdp)
    ) || value.minimum_paths != 1
    {
        return Err(ControlError::Invalid(
            "v6 exit listener supports exactly one general-UDP path",
        ));
    }
    validate_auth_secret(&value.auth_secret)?;
    validate_expiry(value.expires_at_ms)?;
    if value.exit_spki_sha256.len() != 32 || value.exit_spki_sha256.iter().all(|byte| *byte == 0) {
        return Err(ControlError::Invalid(
            "SPKI pin must be a non-zero 32-byte value",
        ));
    }
    validate_tls_server_name(&value.tls_server_name)?;
    validate_exit_overlay_tuple(value)?;
    validate_pem(
        &value.tls_certificate_pem,
        MAX_TLS_CERTIFICATE_PEM,
        "invalid in-memory TLS certificate",
    )?;
    validate_pem(
        &value.tls_private_key_pem,
        MAX_TLS_PRIVATE_KEY_PEM,
        "invalid in-memory TLS private key",
    )?;
    validate_signed_route_fields(
        &value.reservation_id,
        &value.finalize_id,
        &value.auth_secret,
        &value.auth_commitment,
        &value.certificate_sha256,
        &value.client_native_instance_id,
        &value.exit_native_instance_id,
    )?;
    Ok(())
}

fn validate_exit_overlay_tuple(value: &StartExitSession) -> Result<(), ControlError> {
    const OVERLAY_PREFIX: [u8; 6] = [0xfd, 0x76, 0x6f, 0x6c, 0x70, 0x61];

    let valid_overlay = value.listener_ip.len() == 16
        && value.expected_client_ip.len() == 16
        && value.listener_ip.starts_with(&OVERLAY_PREFIX)
        && value.expected_client_ip.starts_with(&OVERLAY_PREFIX)
        && value.listener_ip[..14] == value.expected_client_ip[..14]
        && u16::from_be_bytes([value.listener_ip[10], value.listener_ip[11]])
            == u16::try_from(value.path_id).unwrap_or(0)
        && u16::from_be_bytes([value.listener_ip[14], value.listener_ip[15]]) == 4
        && u16::from_be_bytes([value.expected_client_ip[14], value.expected_client_ip[15]]) == 1;
    if value.path_id == 0
        || value.path_id > 8
        || !valid_overlay
        || !(1..=65_535).contains(&value.listener_port)
        || !(1..=65_535).contains(&value.expected_client_port)
        || value.reservation_hash.len() != 32
        || value.reservation_hash.iter().all(|byte| *byte == 0)
    {
        return Err(ControlError::Invalid(
            "StartExitSession must name one canonical client-to-exit overlay listener",
        ));
    }
    Ok(())
}

fn validate_pem(
    value: &[u8],
    maximum: usize,
    diagnostic: &'static str,
) -> Result<(), ControlError> {
    if value.is_empty() || value.len() > maximum || value.contains(&0) {
        return Err(ControlError::Invalid(diagnostic));
    }
    Ok(())
}

fn validate_masque_context(value: u64) -> Result<(), ControlError> {
    if value == 0 || value > MAX_MASQUE_CONTEXT_ID {
        return Err(ControlError::Invalid(
            "MASQUE context ID must be a non-zero 62-bit value",
        ));
    }
    Ok(())
}

fn validate_ip_packet(packet: &[u8]) -> Result<(), ControlError> {
    if packet.len() < 20 || packet.len() > MAX_INNER_PACKET {
        return Err(ControlError::Invalid("invalid inner IP datagram length"));
    }
    match packet[0] >> 4 {
        4 => {
            let header_len = usize::from(packet[0] & 0x0f) * 4;
            let total_len = usize::from(u16::from_be_bytes([packet[2], packet[3]]));
            if header_len < 20 || header_len > packet.len() || total_len != packet.len() {
                return Err(ControlError::Invalid("malformed IPv4 datagram"));
            }
        }
        6 => {
            if packet.len() < 40 {
                return Err(ControlError::Invalid("truncated IPv6 datagram"));
            }
            let payload_len = usize::from(u16::from_be_bytes([packet[4], packet[5]]));
            if payload_len == 0 || payload_len + 40 != packet.len() {
                return Err(ControlError::Invalid("malformed IPv6 datagram"));
            }
        }
        _ => return Err(ControlError::Invalid("inner datagram is not IPv4/IPv6")),
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    const TEST_AUTH_SECRET: &[u8; AUTH_SECRET_LEN] = b"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    fn test_auth_commitment() -> Vec<u8> {
        let mut hasher = Sha256::new();
        hasher.update(NATIVE_ROUTE_AUTH_COMMITMENT_DOMAIN);
        hasher.update(TEST_AUTH_SECRET);
        hasher.finalize().to_vec()
    }

    fn request(operation: native_request::Operation) -> NativeRequest {
        let target_native_instance_id = match &operation {
            native_request::Operation::Preflight(_) => Vec::new(),
            native_request::Operation::StartSession(value) => {
                value.client_native_instance_id.clone()
            }
            native_request::Operation::StartExitSession(value) => {
                value.exit_native_instance_id.clone()
            }
            _ => vec![9; 32],
        };
        NativeRequest {
            api_version: NATIVE_API_VERSION,
            request_nonce: vec![7; 16],
            target_native_instance_id,
            operation: Some(operation),
        }
    }

    fn start(mode: TransportMode, minimum_paths: u32, context: u64) -> StartSession {
        StartSession {
            route_context_id: vec![1; 16],
            exit_spki_sha256: vec![2; 32],
            minimum_paths,
            masque_context_id: context,
            transport_mode: mode as i32,
            auth_secret: TEST_AUTH_SECRET.to_vec(),
            tls_server_name: b"exit.example".to_vec(),
            expires_at_ms: 1_060_000,
            reservation_id: vec![3; 16],
            finalize_id: vec![4; 16],
            auth_commitment: test_auth_commitment(),
            certificate_sha256: vec![5; 32],
            client_native_instance_id: vec![9; 32],
            exit_native_instance_id: vec![10; 32],
        }
    }

    fn start_exit(mode: TransportMode, minimum_paths: u32, context: u64) -> StartExitSession {
        StartExitSession {
            route_context_id: vec![1; 16],
            auth_secret: TEST_AUTH_SECRET.to_vec(),
            expires_at_ms: 1_060_000,
            minimum_paths,
            masque_context_id: context,
            transport_mode: mode as i32,
            exit_spki_sha256: vec![2; 32],
            tls_server_name: b"exit.example".to_vec(),
            path_id: 1,
            listener_ip: overlay_ip(1, 4),
            listener_port: 443,
            expected_client_ip: overlay_ip(1, 1),
            expected_client_port: 51_820,
            reservation_hash: vec![3; 32],
            tls_certificate_pem: b"-----BEGIN CERTIFICATE-----\nTEST\n-----END CERTIFICATE-----\n"
                .to_vec(),
            tls_private_key_pem: b"-----BEGIN PRIVATE KEY-----\nTEST\n-----END PRIVATE KEY-----\n"
                .to_vec(),
            reservation_id: vec![3; 16],
            finalize_id: vec![4; 16],
            auth_commitment: test_auth_commitment(),
            certificate_sha256: vec![5; 32],
            client_native_instance_id: vec![10; 32],
            exit_native_instance_id: vec![9; 32],
        }
    }

    fn ipv4_packet() -> Vec<u8> {
        let mut packet = vec![0_u8; 20];
        packet[0] = 0x45;
        packet[3] = 20;
        packet
    }

    #[test]
    fn request_round_trip_is_v6_framed_and_validated() {
        let request = request(native_request::Operation::StartSession(start(
            TransportMode::MultipathQuic,
            2,
            3,
        )));
        let frame = encode_request(&request).expect("encode");
        let payload_len = u32::from_be_bytes(frame[..4].try_into().expect("length")) as usize;
        assert_eq!(payload_len, frame.len() - 4);
        assert_eq!(decode_request(&frame[4..]).expect("decode"), request);
    }

    #[test]
    fn preflight_is_the_only_request_with_an_empty_target() {
        let preflight = request(native_request::Operation::Preflight(Preflight {
            expected_role: NativeProcessRole::Client as i32,
        }));
        assert!(preflight.target_native_instance_id.is_empty());
        assert!(encode_request(&preflight).is_ok());

        let mut targeted_preflight = preflight;
        targeted_preflight.target_native_instance_id = vec![9; 32];
        assert!(encode_request(&targeted_preflight).is_err());

        let mut untargeted = request(native_request::Operation::GetStatus(GetStatus {
            route_context_id: vec![1; 16],
        }));
        untargeted.target_native_instance_id.clear();
        assert!(encode_request(&untargeted).is_err());

        let unspecified = request(native_request::Operation::Preflight(Preflight {
            expected_role: NativeProcessRole::Unspecified as i32,
        }));
        assert!(encode_request(&unspecified).is_err());
    }

    #[test]
    fn request_digest_binds_domain_length_target_and_operation() {
        const EXPECTED: [u8; 32] = [
            0x3d, 0xa7, 0x5b, 0xac, 0xc9, 0x56, 0xf3, 0x7f, 0x48, 0x91, 0xab, 0xbd, 0xfc, 0xf9,
            0x2b, 0x78, 0x8b, 0x16, 0x61, 0xab, 0xa8, 0x14, 0x6b, 0xe6, 0xbc, 0x7f, 0x88, 0x13,
            0x75, 0x23, 0x5f, 0xfd,
        ];
        let request = request(native_request::Operation::GetStatus(GetStatus {
            route_context_id: vec![1; 16],
        }));
        let payload = request.encode_to_vec();
        let mut expected = Sha256::new();
        expected.update(b"VOLPAROSSA-MPQUIC-REQUEST-V6\0");
        expected.update(u32::try_from(payload.len()).expect("length").to_be_bytes());
        expected.update(&payload);
        assert_eq!(
            request_sha256(&request).expect("digest"),
            expected.finalize()[..]
        );
        assert_eq!(request_sha256(&request).expect("vector"), EXPECTED);

        let mut other_target = request.clone();
        other_target.target_native_instance_id[0] ^= 1;
        assert_ne!(
            request_sha256(&request).expect("original"),
            request_sha256(&other_target).expect("other target")
        );
    }

    #[test]
    fn signed_route_fields_and_bearer_commitment_fail_closed() {
        let valid = start(TransportMode::MultipathQuic, 2, 3);
        assert!(
            encode_request(&request(native_request::Operation::StartSession(
                valid.clone()
            )))
            .is_ok()
        );

        let mut wrong_bearer = valid.clone();
        wrong_bearer.auth_secret[0] = b'B';
        assert!(
            encode_request(&request(native_request::Operation::StartSession(
                wrong_bearer
            )))
            .is_err()
        );

        let mut missing_signed_id = valid.clone();
        missing_signed_id.finalize_id.clear();
        assert!(
            encode_request(&request(native_request::Operation::StartSession(
                missing_signed_id
            )))
            .is_err()
        );

        let mut wrong_target = request(native_request::Operation::StartSession(valid));
        wrong_target.target_native_instance_id = vec![11; 32];
        assert!(encode_request(&wrong_target).is_err());
    }

    #[test]
    fn response_requires_identity_digest_and_canonical_tunnel_assignment() {
        let request = request(native_request::Operation::GetStatus(GetStatus {
            route_context_id: vec![1; 16],
        }));
        let mut response = NativeResponse {
            api_version: NATIVE_API_VERSION,
            request_nonce: request.request_nonce.clone(),
            result: NativeResultCode::Ok as i32,
            diagnostic_code: "OK".to_owned(),
            paths: Vec::new(),
            received_datagram: None,
            process_identity: Some(NativeProcessIdentity {
                role: NativeProcessRole::Client as i32,
                native_instance_id: vec![9; 32],
            }),
            request_sha256: request_sha256(&request).expect("digest").to_vec(),
            tunnel_assignment: Some(TunnelAssignment {
                assigned_ipv4: [10, 76, 0, 2].to_vec(),
                assigned_prefix_v4: 32,
                server_ipv4: [10, 76, 0, 1].to_vec(),
                server_prefix_v4: 32,
                mtu: 1_280,
                assigned_ipv6: Vec::new(),
                assigned_prefix_v6: 0,
            }),
        };
        assert!(encode_response(&response).is_ok());

        response.result = NativeResultCode::Transport as i32;
        assert!(encode_response(&response).is_err());
        response.result = NativeResultCode::Ok as i32;
        response.api_version = NATIVE_API_VERSION - 1;
        assert!(encode_response(&response).is_err());
        response.api_version = NATIVE_API_VERSION;
        response.request_sha256.fill(0);
        assert!(encode_response(&response).is_ok());
        response.request_sha256.clear();
        assert!(encode_response(&response).is_err());
        response.request_sha256 = request_sha256(&request).expect("digest").to_vec();
        response.process_identity = None;
        assert!(encode_response(&response).is_err());
        response.process_identity = Some(NativeProcessIdentity {
            role: NativeProcessRole::Client as i32,
            native_instance_id: vec![9; 32],
        });
        response
            .tunnel_assignment
            .as_mut()
            .expect("assignment")
            .assigned_prefix_v6 = 96;
        assert!(encode_response(&response).is_err());
    }

    #[test]
    fn tunnel_assignment_rejects_zero_and_aliased_addresses() {
        let valid = TunnelAssignment {
            assigned_ipv4: [10, 76, 0, 2].to_vec(),
            assigned_prefix_v4: 32,
            server_ipv4: [10, 76, 0, 1].to_vec(),
            server_prefix_v4: 32,
            mtu: 1_280,
            assigned_ipv6: [
                0xfd, 0x76, 0x6f, 0x6c, 0x70, 0x61, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2,
            ]
            .to_vec(),
            assigned_prefix_v6: 126,
        };
        assert!(validate_tunnel_assignment(&valid).is_ok());

        let mut zero_client_v4 = valid.clone();
        zero_client_v4.assigned_ipv4.fill(0);
        assert!(validate_tunnel_assignment(&zero_client_v4).is_err());

        let mut zero_server_v4 = valid.clone();
        zero_server_v4.server_ipv4.fill(0);
        assert!(validate_tunnel_assignment(&zero_server_v4).is_err());

        let mut aliased_v4 = valid.clone();
        aliased_v4.server_ipv4 = aliased_v4.assigned_ipv4.clone();
        assert!(validate_tunnel_assignment(&aliased_v4).is_err());

        let mut zero_v6 = valid;
        zero_v6.assigned_ipv6.fill(0);
        assert!(validate_tunnel_assignment(&zero_v6).is_err());
    }

    #[test]
    fn noncanonical_protobuf_forms_are_rejected() {
        let valid = request(native_request::Operation::StartSession(start(
            TransportMode::MultipathQuic,
            2,
            3,
        )))
        .encode_to_vec();
        assert_eq!(valid[..2], [0x08, 0x06]);

        let mut overlong_version = valid.clone();
        overlong_version.splice(1..2, [0x86, 0x00]);
        assert!(decode_request(&overlong_version).is_err());

        let mut unknown = valid.clone();
        unknown.extend_from_slice(&[0x90, 0x01, 0x01]);
        assert!(decode_request(&unknown).is_err());

        let mut duplicate = valid;
        duplicate.extend_from_slice(&[0x08, 0x06]);
        assert!(decode_request(&duplicate).is_err());
    }

    #[test]
    fn old_v2_start_shape_is_rejected_and_start_exit_is_typed() {
        let mut legacy = request(native_request::Operation::StartSession(start(
            TransportMode::MultipathQuic,
            2,
            3,
        )));
        let Some(native_request::Operation::StartSession(value)) = legacy.operation.as_mut() else {
            panic!("start operation");
        };
        value.auth_secret.clear();
        value.tls_server_name.clear();
        value.expires_at_ms = 0;
        let legacy_bytes = legacy.encode_to_vec();
        assert!(decode_request(&legacy_bytes).is_err());

        let start_exit = request(native_request::Operation::StartExitSession(start_exit(
            TransportMode::SinglePathGeneralUdp,
            1,
            19,
        )));
        let frame = encode_request(&start_exit).expect("start exit encode");
        assert_eq!(decode_request(&frame[4..]).expect("decode"), start_exit);
    }

    #[test]
    fn credentials_tls_name_and_expiry_are_bounded() {
        let mut invalid = start(TransportMode::MultipathQuic, 2, 3);
        invalid.auth_secret.clear();
        assert!(
            encode_request(&request(native_request::Operation::StartSession(invalid))).is_err()
        );

        let mut invalid = start(TransportMode::MultipathQuic, 2, 3);
        invalid.auth_secret = vec![1; MAX_AUTH_SECRET + 1];
        assert!(
            encode_request(&request(native_request::Operation::StartSession(invalid))).is_err()
        );

        let mut invalid = start(TransportMode::MultipathQuic, 2, 3);
        invalid.auth_secret[AUTH_SECRET_LEN - 1] = b'B';
        assert!(
            encode_request(&request(native_request::Operation::StartSession(invalid))).is_err()
        );

        for name in [b"-bad.example".as_slice(), b"bad..example", b"bad_name"] {
            let mut invalid = start(TransportMode::MultipathQuic, 2, 3);
            invalid.tls_server_name = name.to_vec();
            assert!(
                encode_request(&request(native_request::Operation::StartSession(invalid))).is_err()
            );
        }

        let mut invalid_exit = start_exit(TransportMode::SinglePathGeneralUdp, 1, 19);
        invalid_exit.expires_at_ms = 0;
        assert!(
            encode_request(&request(native_request::Operation::StartExitSession(
                invalid_exit
            )))
            .is_err()
        );
    }

    #[test]
    fn transport_mode_enforces_exact_path_shape_without_downgrade() {
        assert!(
            encode_request(&request(native_request::Operation::StartSession(start(
                TransportMode::MultipathQuic,
                2,
                3,
            ))))
            .is_ok()
        );
        assert!(
            encode_request(&request(native_request::Operation::StartSession(start(
                TransportMode::SinglePathGeneralUdp,
                1,
                4,
            ))))
            .is_ok()
        );
        for invalid in [
            start(TransportMode::MultipathQuic, 1, 3),
            start(TransportMode::SinglePathGeneralUdp, 2, 3),
            start(TransportMode::Unspecified, 1, 3),
        ] {
            assert!(
                encode_request(&request(native_request::Operation::StartSession(invalid))).is_err()
            );
        }
    }

    #[test]
    fn old_unknown_context_and_nonce_fail_closed() {
        let mut invalid = request(native_request::Operation::StartSession(start(
            TransportMode::MultipathQuic,
            2,
            3,
        )));
        for version in [1, 2, 3, 4, 5, 99] {
            invalid.api_version = version;
            assert!(encode_request(&invalid).is_err());
        }
        invalid.api_version = NATIVE_API_VERSION;
        invalid.request_nonce.fill(0);
        assert!(encode_request(&invalid).is_err());

        invalid.request_nonce.fill(7);
        {
            let Some(native_request::Operation::StartSession(value)) = invalid.operation.as_mut()
            else {
                panic!("start operation");
            };
            value.masque_context_id = 0;
        }
        assert!(encode_request(&invalid).is_err());
        {
            let Some(native_request::Operation::StartSession(value)) = invalid.operation.as_mut()
            else {
                panic!("start operation");
            };
            value.masque_context_id = MAX_MASQUE_CONTEXT_ID + 1;
        }
        assert!(encode_request(&invalid).is_err());
    }

    fn overlay_ip(path_id: u8, host: u8) -> Vec<u8> {
        [
            0xfd, 0x76, 0x6f, 0x6c, 0x70, 0x61, 0x11, 0x11, 0x22, 0x22, 0, path_id, 0x33, 0x33, 0,
            host,
        ]
        .to_vec()
    }

    fn valid_add_path() -> AddPath {
        AddPath {
            route_context_id: vec![1; 16],
            path_id: 1,
            local_port: 51_820,
            local_ip: overlay_ip(1, 1),
            remote_ip: overlay_ip(1, 4),
            remote_port: 443,
            reservation_hash: vec![2; 32],
        }
    }

    #[test]
    fn path_requires_canonical_private_overlay_shape_and_tuple() {
        let valid = request(native_request::Operation::AddPath(valid_add_path()));
        let frame = encode_request(&valid).expect("canonical AddPath");
        assert_eq!(decode_request(&frame[4..]).expect("decode"), valid);

        let rejected = |value| {
            assert!(encode_request(&request(native_request::Operation::AddPath(value))).is_err());
        };

        let mut invalid = valid_add_path();
        invalid.local_port = 0;
        rejected(invalid);

        let mut invalid = valid_add_path();
        invalid.local_ip = [127, 0, 0, 1].to_vec();
        invalid.remote_ip = [192, 0, 2, 4].to_vec();
        rejected(invalid);

        let mut invalid = valid_add_path();
        invalid.local_ip[0] = 0x20;
        invalid.remote_ip[0] = 0x20;
        rejected(invalid);

        let mut invalid = valid_add_path();
        invalid.local_ip[11] = 2;
        invalid.remote_ip[11] = 2;
        rejected(invalid);

        let mut invalid = valid_add_path();
        invalid.remote_ip[13] ^= 1;
        rejected(invalid);

        let mut invalid = valid_add_path();
        invalid.local_ip[15] = 2;
        rejected(invalid);

        let mut invalid = valid_add_path();
        invalid.remote_ip[15] = 3;
        rejected(invalid);
    }

    #[test]
    fn send_and_receive_require_context_and_complete_bounded_packet() {
        let packet = ipv4_packet();
        let send = request(native_request::Operation::SendDatagram(SendDatagram {
            route_context_id: vec![1; 16],
            inner_ip_packet: packet.clone(),
            masque_context_id: 9,
        }));
        let frame = encode_request(&send).expect("send encode");
        assert_eq!(decode_request(&frame[4..]).expect("send decode"), send);

        let receive = request(native_request::Operation::ReceiveDatagram(
            ReceiveDatagram {
                route_context_id: vec![1; 16],
                masque_context_id: 9,
            },
        ));
        let frame = encode_request(&receive).expect("receive encode");
        assert_eq!(
            decode_request(&frame[4..]).expect("receive decode"),
            receive
        );

        let mut zero = send.clone();
        {
            let Some(native_request::Operation::SendDatagram(value)) = zero.operation.as_mut()
            else {
                panic!("send operation");
            };
            value.inner_ip_packet.clear();
        }
        assert!(encode_request(&zero).is_err());
        {
            let Some(native_request::Operation::SendDatagram(value)) = zero.operation.as_mut()
            else {
                panic!("send operation");
            };
            value.inner_ip_packet = vec![0_u8; MAX_INNER_PACKET + 1];
            value.inner_ip_packet[0] = 0x45;
        }
        assert!(encode_request(&zero).is_err());
        {
            let Some(native_request::Operation::SendDatagram(value)) = zero.operation.as_mut()
            else {
                panic!("send operation");
            };
            value.inner_ip_packet = packet;
            value.masque_context_id = 0;
        }
        assert!(encode_request(&zero).is_err());
    }

    #[test]
    fn reverse_response_round_trips_and_can_be_wiped() {
        let mut response = NativeResponse {
            api_version: NATIVE_API_VERSION,
            request_nonce: vec![5; 16],
            result: NativeResultCode::Ok as i32,
            diagnostic_code: "datagram".to_owned(),
            paths: Vec::new(),
            received_datagram: Some(ReceivedDatagram {
                route_context_id: vec![1; 16],
                masque_context_id: 9,
                inner_ip_packet: ipv4_packet(),
            }),
            process_identity: Some(NativeProcessIdentity {
                role: NativeProcessRole::Client as i32,
                native_instance_id: vec![9; 32],
            }),
            request_sha256: vec![8; 32],
            tunnel_assignment: None,
        };
        let frame = encode_response(&response).expect("response encode");
        response
            .received_datagram
            .as_mut()
            .expect("datagram")
            .wipe();
        assert!(
            response
                .received_datagram
                .as_ref()
                .expect("datagram")
                .inner_ip_packet
                .is_empty()
        );
        let decoded = decode_response(&frame[4..]).expect("response decode");
        assert_eq!(
            decoded
                .received_datagram
                .as_ref()
                .expect("decoded datagram")
                .masque_context_id,
            9
        );

        let mut overflow = decoded;
        overflow.result = NativeResultCode::QueueOverflow as i32;
        assert!(encode_response(&overflow).is_err());
        overflow.received_datagram = None;
        assert!(encode_response(&overflow).is_ok());
    }
}
